#if canImport(SwiftUI)
import SwiftUI
import ScenarioEngine

@available(iOS 18.0, macOS 15.0, *)
public struct Rev35PlayableDeepSystemsView: View {
    @State private var runtime=Rev35PlayableDeepRuntime()
    public init(){}
    public var body: some View { NavigationStack { ScrollView { VStack(spacing:16){
        header; vision; meter; scope; thermal; ladder; schematic; academy; forensic; workOrder
    }.padding() }.navigationTitle("Playable Systems Lab") }.preferredColorScheme(.dark).tint(.cyan) }
    private var header:some View { VStack(alignment:.leading,spacing:6){Text("REV35 · ONE MACHINE, MANY INSTRUMENTS").font(.caption.bold()).foregroundStyle(.cyan);Text("Measure the same physical truth from every surface.").font(.title2.bold());Text("Electrical Vision, physical probes, scope, thermal imaging, ladder, schematic and work-order evidence stay tied to canonical identities.").foregroundStyle(.secondary)}.frame(maxWidth:.infinity,alignment:.leading) }
    private var vision:some View { GroupBox("Electrical Vision") { HStack{ForEach(runtime.visionFrame.samples,id:\.identity){s in VStack(spacing:5){Image(systemName:s.temperatureC > 45 ? "thermometer.high":"bolt.fill").font(.title2);Text(s.identity).bold();Text(String(format:"%.2f mA",s.amps*1000)).monospacedDigit();Text(String(format:"%.0f °C",s.temperatureC)).font(.caption);ProgressView(value:s.quality)}.frame(maxWidth:.infinity)}} } }
    private var meter:some View { GroupBox("Physical DMM") { VStack{HStack{Picker("Function",selection:$runtime.dmm.function){ForEach(EEMeterFunction.allCases,id:\.self){Text($0.rawValue).tag($0)}};Picker("Red jack",selection:$runtime.dmm.redJack){ForEach(EEProbeJack.allCases,id:\.self){Text($0.rawValue).tag($0)}}};HStack{Button("Red → DISC-401"){runtime.dmm.placement.red="DISC-401"};Button("Black → COM"){runtime.dmm.placement.black="COM"};Spacer();Text(runtime.dmm.validate(energized:true).rawValue).font(.caption.bold())}.buttonStyle(.bordered)} } }
    private var scope:some View { GroupBox("Oscilloscope / waveform recorder") { Canvas{ctx,size in guard let pts=runtime.scope.channels.first?.points, let maxT=pts.last?.t else{return};var p=Path();for (i,v) in pts.enumerated(){let x=maxT == 0 ? 0:v.t/maxT*size.width;let y=size.height/2-(v.value-12)*size.height; if i==0{p.move(to:.init(x:x,y:y))}else{p.addLine(to:.init(x:x,y:y))}};ctx.stroke(p,with:.color(.cyan),lineWidth:2)}.frame(height:120).background(.black.opacity(0.4),in:RoundedRectangle(cornerRadius:10)) } }
    private var thermal:some View { GroupBox("Thermal camera") { LazyVGrid(columns:Array(repeating:GridItem(.flexible(),spacing:3),count:runtime.thermal.width),spacing:3){ForEach(runtime.thermal.pixels,id:\.self){p in ZStack{Rectangle().fill(p.celsius > 45 ? Color.orange:Color.blue.opacity(0.45)).aspectRatio(1,contentMode:.fit);VStack{Text(String(format:"%.0f°",p.celsius)).font(.caption.bold());if let id=p.identity{Text(id).font(.system(size:8))}}}}};if let hot=runtime.thermal.hottest {Text("Hottest point: \(hot.identity ?? "unidentified") · \(Int(hot.celsius)) °C").font(.caption.bold()).padding(.top,6)} } }
    private var ladder:some View { GroupBox("Live ladder + cross-reference") { VStack(alignment:.leading){ForEach(runtime.ladder.rungs,id:\.number){r in HStack{Text("R\(r.number)").monospacedDigit();ForEach(r.contacts,id:\.tag){c in Text("[ \(c.tag) ]").padding(5).background(c.state ? Color.green.opacity(0.25):Color.gray.opacity(0.2),in:RoundedRectangle(cornerRadius:5))};Spacer();Text("( \(r.outputTag) )").bold().foregroundStyle(r.energized ? .green:.secondary)}}} } }
    private var schematic:some View { GroupBox("Interactive schematic projection") { ScrollView(.horizontal){HStack(spacing:5){ForEach(Array(runtime.schematic.nodes.enumerated()),id:\.element.identity){i,n in Button(n.label){}.buttonStyle(.borderedProminent);if i < runtime.schematic.nodes.count-1 {Image(systemName:"arrow.right").foregroundStyle(.green)}}}.padding(.vertical,4)} } }
    private var academy:some View { GroupBox("Motor Academy · 26 executable lessons") { ScrollView(.horizontal){HStack{ForEach(runtime.motorAcademy.exercises.prefix(10),id:\.lesson){e in VStack(alignment:.leading){Text(e.lesson.rawValue).bold();Text(e.objective).font(.caption).foregroundStyle(.secondary).lineLimit(3);Text("Build · Fault · Prove").font(.caption2).foregroundStyle(.cyan)}.frame(width:160,height:100,alignment:.topLeading).padding(8).background(.thinMaterial,in:RoundedRectangle(cornerRadius:12))}}} } }
    private var forensic:some View { GroupBox("Historian / SOE forensics") { VStack(alignment:.leading){ForEach(runtime.workOrder.timeline.events,id:\.sequence){e in HStack{Text(String(format:"%05.1f",e.t)).monospacedDigit();Text(e.kind.rawValue).font(.caption).foregroundStyle(.cyan);Text(e.identity).bold();Spacer();Text(e.value).font(.caption)}};if runtime.workOrder.timeline.events.isEmpty{Text("Actions in the work order populate this timeline automatically.").foregroundStyle(.secondary)}} } }
    private var workOrder:some View { GroupBox("WO-401 · End-to-end playable case") { VStack(alignment:.leading,spacing:10){LabeledContent("State",value:runtime.workOrder.state.rawValue.uppercased());ProgressView(value:runtime.workOrder.journey.progress);HStack{Button("Accept"){runtime.workOrder.accept()};Button("Isolate"){runtime.workOrder.isolate()};Button("Repair"){runtime.workOrder.repair()};Button("Recommission"){runtime.workOrder.recommission()};Button("Verify"){runtime.workOrder.verify()};Button("Close"){runtime.workOrder.close()}}.buttonStyle(.bordered).controlSize(.small);Text(runtime.workOrder.proof.readyToClose ? "ROOT CAUSE CORRECTED · PROOF COMPLETE":"Closure remains gated by physical repair and proof evidence.").font(.caption.bold()).foregroundStyle(runtime.workOrder.proof.readyToClose ? .green:.orange)} } }
}
#endif
