#if canImport(SwiftUI)
import SwiftUI
import ScenarioEngine
@available(iOS 18.0, macOS 15.0, *)
public struct Rev48ProductionShell:View {@State private var model=EERev48InteractiveForensics();public init(){};public var body:some View{NavigationStack{List{Section("Operate"){NavigationLink("Natural Gas Operating World"){Rev48World(model:$model,world:.naturalGas)};NavigationLink("Coal & Mining Operating World"){Rev48World(model:$model,world:.coalMining)}};Section("Learn & Build"){NavigationLink("Interactive Electronics Bench"){Rev48Bench(model:$model)};NavigationLink("Training Qualifications"){Rev48Training(model:$model)}};Section("Diagnose"){NavigationLink("Evidence Board + Next Tests"){Rev48Evidence(model:$model)};NavigationLink("Universal Golden Thread"){Rev47Golden(model:$model.base)};NavigationLink("Forensic Timeline"){Rev46TimelineView(model:$model.base.base)}}}.navigationTitle("Electric Engineer · Rev48")}}}
@available(iOS 18.0, macOS 15.0, *) struct Rev48Bench:View{@Binding var model:EERev48InteractiveForensics;@State var from="PS1:+";@State var to="R1:1";var body:some View{List{Section("Physical Components"){ForEach(model.bench.components){c in VStack(alignment:.leading){Text(c.id).bold();Text(c.kind.rawValue);Text(c.terminals.joined(separator:" · ")).font(.caption).monospaced()}}};Section("Point-to-Point Wiring"){TextField("From terminal",text:$from);TextField("To terminal",text:$to);Button("Land conductor"){if model.bench.terminalExists(from)&&model.bench.terminalExists(to){model.bench.wire(from,to)}};ForEach(model.bench.wires){w in HStack{Text("\(w.from) → \(w.to)").monospaced();Spacer();Button("Remove"){model.bench.removeWire(w.id)}}}}}.navigationTitle("Electronics Bench")}}
@available(iOS 18.0, macOS 15.0, *) struct Rev48Training:View{@Binding var model:EERev48InteractiveForensics;var body:some View{List{ForEach(model.training.qualifications){q in Section(q.school.rawValue){ForEach(EETrainingStage48.allCases,id:\.self){s in HStack{Image(systemName:q.stages[s] == true ? "checkmark.circle.fill":"circle");Text(s.rawValue.capitalized);Spacer();Button("Pass"){model.training.pass(s,school:q.school,evidence:1)}.disabled(q.stages[s] == true)}};LabeledContent("Evidence",value:"\(q.evidenceCount)")}}}.navigationTitle("Training Qualifications")}}
@available(iOS 18.0, macOS 15.0, *) struct Rev48Evidence:View{@Binding var model:EERev48InteractiveForensics;var target:String{model.selectedAsset ?? (model.selectedWorld == .naturalGas ? "PIT-401":"CV-NR-OL")};var body:some View{List{Section("Hypotheses"){ForEach(model.base.board.ranked){h in LabeledContent(h.title,value:h.probability.formatted(.percent.precision(.fractionLength(1))))}};Section("Next discriminating tests"){ForEach(model.planner.nextTests(board:model.base.board,world:model.selectedWorld,asset:target)){t in VStack(alignment:.leading){Text(t.title).bold();Text("\(t.instrument.rawValue) · \(t.target)").font(.caption);Text(t.rationale).foregroundStyle(.secondary)}}};Section("Evidence"){ForEach(model.base.board.cards){c in VStack(alignment:.leading){Text(c.statement).bold();Text("\(c.identity) · \(c.value)").font(.caption);Text("t=\(c.time.formatted()) · \(c.world.rawValue)").font(.caption2)}}}}.navigationTitle("Evidence & Hypotheses")}}
@available(iOS 18.0, macOS 15.0, *) struct Rev48World:View{@Binding var model:EERev48InteractiveForensics;let world:EEIndustrialWorld;@State var instrument:EEInstrumentKind = .dmm;var channels:[EEForensicChannel]{model.base.base.timeline.snapshots(for:world).last?.channels ?? []};var body:some View{List{Section("Facility route"){ForEach(model.navigation.locations.assets(in:world)){a in Button{model.selectedWorld=world;model.travel(to:a.id)}label:{HStack{Image(systemName:model.selectedAsset==a.id ? "location.fill":"location");VStack(alignment:.leading){Text(a.id).bold();Text(a.zone).font(.caption)};Spacer();Text(a.kind).foregroundStyle(.secondary)}}}};if let id=model.selectedAsset,let a=model.navigation.locations.assets.first(where:{$0.id==id && $0.world==world}){Section("At \(a.zone) · \(id)"){Picker("Instrument",selection:$instrument){ForEach(EEInstrumentKind.allCases,id:\.self){Text($0.rawValue).tag($0)}};ForEach(channels.filter{$0.sourceIdentity==id}){c in Button("Measure \(c.label)"){let rule=model.placement.rule(for:instrument);let points=rule == .twoPointElectrical ? ["lead-A","lead-B"]:["target"];_ = model.measure(world:world,asset:id,channelID:c.id,instrument:instrument,points:points)}};ForEach(model.navigation.neighbors(of:id,world:world),id:\.self){n in Button("Walk to \(n)"){model.travel(to:n)}};NavigationLink("Trace \(id) in Golden Thread"){Rev47Golden(model:$model.base,q:id)}}};Section("Live truth"){ForEach(channels){c in LabeledContent(c.label,value:"\(c.value.formatted(.number.precision(.fractionLength(2)))) \(c.unit)")}};Button("Advance this world 5 s"){if world == .naturalGas{model.base.base.advanceGas(5)}else{model.base.base.advanceCoal(5)}}}.navigationTitle(world.rawValue)}}
#endif
