#if canImport(SwiftUI)
import SwiftUI
import ScenarioEngine
@available(iOS 18.0, macOS 15.0, *) public struct Rev54ProductionShell:View{@State private var model=EERev54UnifiedSimulation();public init(){};public var body:some View{NavigationStack{List{Section("Unified Bench"){NavigationLink("Physical Circuit + Adaptive Transient"){Rev54Bench(model:$model)};NavigationLink("Scope · Trigger · Cursors · FFT"){Rev54Scope(model:$model)};NavigationLink("Semiconductor Lab"){Rev54Semiconductor(model:$model)}};Section("Control the Same Physics"){NavigationLink("Electromechanical Loop"){Rev54Relay(model:$model)};NavigationLink("Embedded GPIO · PWM · ADC · CAN"){Rev54Embedded(model:$model)}};Section("Full Existing Game"){NavigationLink("Rev53 Simulation Production"){Rev53ProductionShell()};NavigationLink("Industrial Worlds + Forensics"){Rev52ProductionShell()}}}.navigationTitle("Electric Engineer · Rev54")}}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev54Bench:View{@Binding var model:EERev54UnifiedSimulation;var body:some View{List{Picker("Generator",selection:$model.bench.generator.waveform){ForEach(EESignalWaveform53.allCases,id:\.self){Text($0.rawValue).tag($0)}};Button("Run physical RC transient"){_ = model.bench.runGeneratorRC(duration:0.02)};LabeledContent("Accepted steps",value:"\(model.bench.transient.trace.count)");if let x=model.bench.transient.trace.last{LabeledContent("Output",value:"\(x.value.formatted()) V");LabeledContent("Last Δt",value:"\(x.dt.formatted()) s")}}.navigationTitle("Adaptive CircuitMNA")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev54Scope:View{@Binding var model:EERev54UnifiedSimulation;var body:some View{List{LabeledContent("Trigger",value:model.bench.scope.rising ? "Rising":"Falling");LabeledContent("Level",value:"\(model.bench.scope.level.formatted()) V");Text("Trigger, cursor, RMS/frequency and FFT engines operate on simulation samples.").font(.caption)}}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev54Semiconductor:View{@Binding var model:EERev54UnifiedSimulation;var body:some View{List{LabeledContent("BJT Ic @ 1 V base",value:"\(model.bench.nonlinear.bjtCollector(baseV:1).formatted()) A");LabeledContent("MOSFET Id @ 5 V gate",value:"\(model.bench.nonlinear.mosfetDrain(gateV:5).formatted()) A");LabeledContent("Op-amp differential output",value:"\(model.bench.nonlinear.opAmp(vPlus:0.01,vMinus:0).formatted()) V")}.navigationTitle("Semiconductor Lab")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev54Relay:View{@Binding var model:EERev54UnifiedSimulation;var body:some View{List{Button("Energize coil"){for _ in 0..<20{model.bench.electromechanical.step(command:true,dt:0.01)}};Button("Drop coil"){for _ in 0..<20{model.bench.electromechanical.step(command:false,dt:0.01)}};LabeledContent("Contact",value:model.bench.electromechanical.relay.closed ? "Closed":"Open");LabeledContent("Load current",value:"\(model.bench.electromechanical.loadCurrent.formatted()) A")}.navigationTitle("Electromechanical Loop")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev54Embedded:View{@Binding var model:EERev54UnifiedSimulation;var body:some View{List{Button("GPIO HIGH"){model.bench.embedded.writeGPIO("OUT",true)};Button("PWM 60%"){model.bench.embedded.writePWM("MOTOR",0.6)};Button("Sample 2.5 V ADC"){model.bench.embedded.sampleADC("AI0",nodeVoltage:2.5)};LabeledContent("GPIO",value:model.bench.embedded.gpio["OUT"] == true ? "HIGH":"LOW");LabeledContent("PWM",value:"\((model.bench.embedded.pwm["MOTOR"] ?? 0).formatted(.percent))");LabeledContent("ADC",value:"\((model.bench.embedded.adc["AI0"] ?? 0).formatted(.percent))")}.navigationTitle("Embedded I/O")}}
#endif
