#if canImport(SwiftUI)
import SwiftUI
import ScenarioEngine
@available(iOS 18.0, macOS 15.0, *) public struct Rev53ProductionShell:View {@State private var model=EERev53SimulationProduction();public init(){};public var body:some View{NavigationStack{List{Section("Build & Simulate"){NavigationLink("Freeform CircuitMNA Bench"){Rev52ProductionShell()};NavigationLink("Transient & Nonlinear Lab"){Rev53Transient(model:$model)};NavigationLink("Three-Phase Trainer"){Rev53ThreePhase(model:$model)};NavigationLink("Relay / Contactor Mechanics"){Rev53Relay(model:$model)}};Section("Measure & Analyze"){NavigationLink("Function Generator + Oscilloscope"){Rev53Scope(model:$model)};NavigationLink("Engineering Analysis Lab"){Rev53Analysis(model:$model)}};Section("Control"){NavigationLink("Embedded Runtime"){Rev53Embedded(model:$model)};NavigationLink("Rev52 Full Assimilation Workspace"){Rev52ProductionShell()}}}.navigationTitle("Electric Engineer · Rev53")}}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev53Transient:View{@Binding var model:EERev53SimulationProduction;var body:some View{List{Button("Run RC transient"){let r=model.transient.rcStep();model.scope.capture(id:"CH1",terminal:"C1",values:r.voltages["C1"] ?? [])};Button("Solve diode operating point"){_ = model.transient.diodeOperatingPoint()};LabeledContent("Transient steps",value:"\(model.transient.trace.convergedSteps)")}.navigationTitle("Transient + Nonlinear")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev53ThreePhase:View{@Binding var model:EERev53SimulationProduction;var body:some View{List{LabeledContent("Line voltage",value:"\(model.threePhase.lineVolts.formatted()) V");LabeledContent("Frequency",value:"\(model.threePhase.frequencyHz.formatted()) Hz");Toggle("ABC sequence",isOn:$model.threePhase.phaseSequenceABC);ForEach(Array(model.threePhase.phaseVoltages(at:0.001).enumerated()),id:\.offset){i,v in LabeledContent("Phase \(i+1)",value:"\(v.formatted(.number.precision(.fractionLength(1)))) V")}}.navigationTitle("Three-Phase Trainer")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev53Relay:View{@Binding var model:EERev53SimulationProduction;var body:some View{List{Button("Energize coil"){model.relay.coilVolts=model.relay.ratedVolts;for _ in 0..<10{model.relay.step(dt:0.01)}};Button("Drop coil"){model.relay.coilVolts=0;for _ in 0..<10{model.relay.step(dt:0.01)}};LabeledContent("Armature",value:model.relay.armature.formatted(.percent));LabeledContent("Contact",value:model.relay.closed ? "Closed":"Open");LabeledContent("Cycles",value:"\(model.relay.cycles)")}.navigationTitle("Relay Mechanics")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev53Scope:View{@Binding var model:EERev53SimulationProduction;var body:some View{List{Picker("Waveform",selection:$model.generator.waveform){ForEach(EESignalWaveform53.allCases,id:\.self){Text($0.rawValue).tag($0)}};LabeledContent("Frequency",value:"\(model.generator.frequencyHz.formatted()) Hz");Button("Capture generator"){let vals=(0..<500).map{model.generator.value(at:Double($0)/100_000)};model.scope.capture(id:"CH1",terminal:"GEN",values:vals)};ForEach(model.scope.channels){c in LabeledContent(c.id,value:"\(c.samples.count) samples")}}.navigationTitle("Generator + Scope")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev53Analysis:View{@Binding var model:EERev53SimulationProduction;var body:some View{List{Button("DC Sweep"){_ = model.analysis.dcSweep()};Button("AC Sweep RC"){_ = model.analysis.acSweepRC()};Button("Monte Carlo"){_ = model.analysis.monteCarloResistance()};ForEach(Array(model.analysis.results.enumerated()),id:\.offset){_,r in VStack(alignment:.leading){Text(r.mode.rawValue);Text(r.summary).font(.caption).foregroundStyle(.secondary);Text("\(r.x.count) points").font(.caption2)}}}.navigationTitle("Engineering Analysis")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev53Embedded:View{@Binding var model:EERev53SimulationProduction;let program:[EEEmbeddedInstruction53]=[.set("OUT",1),.add("OUT",1),.copy("OUT","PWM")];var body:some View{List{Button("Single Step"){model.embedded.step(program)};LabeledContent("PC",value:"\(model.embedded.pc)");LabeledContent("State",value:model.embedded.halted ? "Halted":"Running");ForEach(model.embedded.registers.keys.sorted(),id:\.self){k in LabeledContent(k,value:model.embedded.registers[k]!.formatted())}}.navigationTitle("Embedded Runtime")}}
#endif
