#if canImport(SwiftUI)
import SwiftUI
import ScenarioEngine
@available(iOS 18.0, macOS 15.0, *) public struct Rev52ProductionShell:View {@State private var model=EERev52TotalAssimilation();public init(){};public var body:some View{NavigationStack{List{Section("Build & Experiment"){NavigationLink("Seven-Lab Engineering Bench"){Rev52Bench(model:$model)};NavigationLink("Instrument Rack"){Rev52Catalog(title:"Instrument Rack",items:model.instrumentRack.map{$0.rawValue})};NavigationLink("Engineering Analysis"){Rev52Catalog(title:"Analysis Laboratory",items:model.analysisModes.map{$0.rawValue})}};Section("See & Break"){NavigationLink("Electrical Vision"){Rev52Catalog(title:"Electrical Vision",items:model.visionLayers.map{$0.rawValue})};NavigationLink("Fault Laboratory"){Rev52Catalog(title:"Fault Library",items:model.faultLibrary.map{$0.rawValue})}};Section("Trace & Reconstruct"){NavigationLink("Registry-Complete Golden Thread"){Rev52Golden(model:$model)};NavigationLink("Synchronized Forensic Replay"){Rev51ProductionShell()}};Section("Research Assimilation"){NavigationLink("Feature Assimilation Matrix"){Rev52Matrix(model:$model)}}}.navigationTitle("Electric Engineer · Rev52")}}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev52Bench:View {@Binding var model:EERev52TotalAssimilation;var body:some View{List{Picker("Laboratory",selection:$model.bench.selectedLab){ForEach(EELabEnvironment52.allCases,id:\.self){Text($0.rawValue).tag($0)}};Section("CircuitMNA"){Button("Solve physical truth"){_ = model.bench.solve()};if let r=model.bench.core.last{LabeledContent("State",value:r.state.rawValue);LabeledContent("Residual",value:r.residual.formatted());ForEach(r.nodeVoltages){LabeledContent($0.id,value:"\($0.volts.formatted(.number.precision(.fractionLength(3)))) V")}}};Section("Editor"){Button("Undo"){model.bench.undoLast()}.disabled(model.bench.undo.isEmpty);Button("Redo"){model.bench.redoLast()}.disabled(model.bench.redo.isEmpty);LabeledContent("Undo depth",value:"\(model.bench.undo.count)")};Section("Electrical Vision"){ForEach(EEVisionLayer52.allCases,id:\.self){v in Toggle(v.rawValue,isOn:Binding(get:{model.bench.vision.contains(v)},set:{if $0{model.bench.vision.insert(v)}else{model.bench.vision.remove(v)}}))}}}.navigationTitle("Engineering Bench")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev52Catalog:View {let title:String;let items:[String];var body:some View{List(items,id:\.self){Text($0)}.navigationTitle(title)}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev52Matrix:View {@Binding var model:EERev52TotalAssimilation;var body:some View{List{ForEach(EEReferenceProduct52.allCases,id:\.self){p in Section(p.rawValue){ForEach(model.matrix.from(p)){f in VStack(alignment:.leading){Text(f.sourceConcept).bold();Text(f.electricEngineerAdaptation);Text("\(f.domain.rawValue) · \(f.state.rawValue)").font(.caption).foregroundStyle(.secondary)}}}}}.navigationTitle("Assimilation Matrix")}}
@available(iOS 18.0, macOS 15.0, *) private struct Rev52Golden:View {@Binding var model:EERev52TotalAssimilation;@State private var q="";var body:some View{List{Section("Audit"){LabeledContent("Identities",value:"\(model.goldenAudit.total)");LabeledContent("Coverage",value:model.goldenAudit.coverage.formatted(.percent));LabeledContent("Duplicates",value:"\(model.goldenAudit.duplicateKeys.count)")};TextField("Asset, tag, drawing, test point",text:$q);ForEach(model.base.golden.related(q),id:\.id){i in Section(i.id){ForEach(i.bindings,id:\.reference){b in LabeledContent(b.surface.rawValue,value:b.reference)}}}}.navigationTitle("Golden Thread")}}
#endif
