import Foundation
import ElectricalCore
import CircuitMNA

// MARK: - Rev10 physical panel construction
public enum EnclosureRating:String,Sendable,Codable { case indoor, washdown, outdoor, hazardousConcept }
public struct PanelEnclosure:Sendable,Codable,Equatable {
 public var size:PanelSize; public var depthMM:Double; public var rating:EnclosureRating; public var ambientC:Double
 public init(widthMM:Double=800,heightMM:Double=1000,depthMM:Double=300,rating:EnclosureRating = .indoor,ambientC:Double=25){size = .init(widthMM,heightMM);self.depthMM=depthMM;self.rating=rating;self.ambientC=ambientC}
}
public enum AccessoryKind:String,Sendable,Codable { case dinRail, wireDuct, groundBar, endStop, jumper, gland, cordGrip, label, pushbutton, selector, pilotLight, disconnectHandle }
public struct PanelAccessory:Identifiable,Sendable,Codable,Equatable { public var id:String; public var kind:AccessoryKind; public var position:PanelPoint; public var lengthMM:Double; public init(id:String,kind:AccessoryKind,position:PanelPoint,lengthMM:Double=0){self.id=id;self.kind=kind;self.position=position;self.lengthMM=lengthMM} }
public enum TerminationQuality:String,Sendable,Codable { case unstripped, bare, ferruled, lugged }
public struct InstalledTermination:Sendable,Codable,Equatable { public var endpoint:String; public var quality:TerminationQuality; public var torqueNm:Double; public var targetTorqueNm:Double; public var strippedLengthMM:Double; public init(endpoint:String,quality:TerminationQuality,torqueNm:Double,targetTorqueNm:Double,strippedLengthMM:Double=8){self.endpoint=endpoint;self.quality=quality;self.torqueNm=torqueNm;self.targetTorqueNm=targetTorqueNm;self.strippedLengthMM=strippedLengthMM}; public var torqueError:Double{abs(torqueNm-targetTorqueNm)/max(targetTorqueNm,0.01)}; public var acceptable:Bool{quality != .unstripped && torqueError <= 0.20} }
public struct BuiltConductor:Identifiable,Sendable,Codable,Equatable { public var id:String; public var engineered:EngineeredWire; public var cutLengthMM:Double; public var color:String; public var fromTermination:InstalledTermination; public var toTermination:InstalledTermination; public init(id:String,engineered:EngineeredWire,cutLengthMM:Double,color:String,fromTermination:InstalledTermination,toTermination:InstalledTermination){self.id=id;self.engineered=engineered;self.cutLengthMM=cutLengthMM;self.color=color;self.fromTermination=fromTermination;self.toTermination=toTermination}; public var slackMM:Double{cutLengthMM-engineered.lengthMM}; public var buildValid:Bool{slackMM >= 0 && fromTermination.acceptable && toTermination.acceptable} }

// MARK: - Engineering calculations
public struct ControlPowerBudget:Sendable,Equatable { public var supplyVA:Double; public var connectedVA:Double; public init(supplyVA:Double,connectedVA:Double){self.supplyVA=supplyVA;self.connectedVA=connectedVA}; public var spareFraction:Double{max((supplyVA-connectedVA)/max(supplyVA,1e-9),-1)}; public var overloaded:Bool{connectedVA>supplyVA} }
public struct DCLoadBudget:Sendable,Equatable { public var supplyAmps:Double; public var loadAmps:Double; public init(supplyAmps:Double,loadAmps:Double){self.supplyAmps=supplyAmps;self.loadAmps=loadAmps}; public var utilization:Double{loadAmps/max(supplyAmps,1e-9)}; public var overloaded:Bool{loadAmps>supplyAmps} }
public struct VoltageDropResult:Sendable,Equatable { public var resistanceOhms:Double; public var dropVolts:Double; public var percent:Double }
public enum PanelCalculations {
 public static func copperVoltageDrop(lengthM:Double,areaMM2:Double,currentA:Double,systemVolts:Double,roundTrip:Bool=true)->VoltageDropResult { let rho=0.017241; let path=lengthM*(roundTrip ? 2:1); let r=rho*path/max(areaMM2,1e-9); let d=currentA*r; return .init(resistanceOhms:r,dropVolts:d,percent:100*d/max(systemVolts,1e-9)) }
 public static func thermalRiseC(heatWatts:Double,enclosureAreaM2:Double,ventilationWPerC:Double=5)->Double { heatWatts/max(ventilationWPerC*max(enclosureAreaM2,0.1),0.1) }
}
public struct ProtectionDevice:Identifiable,Sendable,Codable,Equatable { public var id:String; public var pickupA:Double; public var instantaneousA:Double; public var interruptRatingKA:Double; public init(id:String,pickupA:Double,instantaneousA:Double,interruptRatingKA:Double){self.id=id;self.pickupA=pickupA;self.instantaneousA=instantaneousA;self.interruptRatingKA=interruptRatingKA} }
public struct CoordinationReport:Sendable,Equatable { public var selective:Bool; public var interruptRatingAdequate:Bool; public var notes:[String] }
public enum ProtectionCoordination { public static func assess(upstream:ProtectionDevice,downstream:ProtectionDevice,availableFaultKA:Double)->CoordinationReport { let selective=upstream.pickupA>downstream.pickupA && upstream.instantaneousA>downstream.instantaneousA; let adequate=min(upstream.interruptRatingKA,downstream.interruptRatingKA)>=availableFaultKA; var n:[String]=[]; if !selective{n.append("Protection curves may overlap")}; if !adequate{n.append("Interrupt rating below available fault current")}; return .init(selective:selective,interruptRatingAdequate:adequate,notes:n) } }

// MARK: - Deeper PLC instruction set
public enum AdvancedInstruction:Sendable,Codable,Equatable { case oneShot(input:String,storage:String,output:String), compareGreater(a:String,b:String,output:String), limit(value:String,low:Double,high:Double,output:String), add(a:String,b:String,destination:String), sub(a:String,b:String,destination:String), mul(a:String,b:String,destination:String), div(a:String,b:String,destination:String), retentiveTimer(tag:String,preset:Double,enable:String), resetTimer(String), stateTransition(stateTag:String,from:Int,to:Int,condition:String) }
public struct AdvancedAutomationRuntime:Sendable { public var base=AutomationRuntime(); public var retentiveTimers:[String:PLCTimer]=[:]; public var lastBits:[String:Bool]=[:]; public var ints:[String:Int]=[:]; public init(){}; public mutating func execute(_ i:AdvancedInstruction,dt:Double=0.01){ switch i { case .oneShot(let input,let storage,let output): let now=base.bools[input] ?? false; let last=lastBits[storage] ?? false; base.bools[output]=now && !last; lastBits[storage]=now; case .compareGreater(let a,let b,let o): base.bools[o]=(base.reals[a] ?? 0)>(base.reals[b] ?? 0); case .limit(let v,let l,let h,let o): let x=base.reals[v] ?? 0;base.bools[o]=x>=l && x<=h; case .add(let a,let b,let d):base.reals[d]=(base.reals[a] ?? 0)+(base.reals[b] ?? 0); case .sub(let a,let b,let d):base.reals[d]=(base.reals[a] ?? 0)-(base.reals[b] ?? 0); case .mul(let a,let b,let d):base.reals[d]=(base.reals[a] ?? 0)*(base.reals[b] ?? 0); case .div(let a,let b,let d):base.reals[d]=(base.reals[a] ?? 0)/max(abs(base.reals[b] ?? 0),1e-12); case .retentiveTimer(let tag,let preset,let enable): var t=retentiveTimers[tag] ?? .init(preset:preset);t.preset=preset;if base.bools[enable] ?? false{t.accumulated += dt};t.done=t.accumulated+1e-12>=preset;retentiveTimers[tag]=t;base.bools[tag+".DN"]=t.done; case .resetTimer(let tag):retentiveTimers[tag]=nil;base.bools[tag+".DN"]=false; case .stateTransition(let tag,let from,let to,let condition):if (ints[tag] ?? 0)==from && (base.bools[condition] ?? false){ints[tag]=to} } } }

// MARK: - Process truth and closed-loop automation
public struct ProcessTank:Sendable,Codable,Equatable { public var levelPercent:Double=50; public var capacityLiters:Double=1000; public var inletLPS:Double=0; public var outletLPS:Double=0; public init(){}; public mutating func step(dt:Double){let delta=(inletLPS-outletLPS)*dt/max(capacityLiters,1)*100;levelPercent=min(max(levelPercent+delta,0),100)} }
public struct ControlValve:Sendable,Codable,Equatable { public var commandPercent:Double=0; public var actualPercent:Double=0; public var strokeSeconds:Double=2; public var stuck=false; public init(){}; public mutating func step(dt:Double){guard !stuck else{return};let maxMove=100*dt/max(strokeSeconds,0.01);actualPercent += min(max(commandPercent-actualPercent,-maxMove),maxMove)} }
public struct ClosedLoopLevelCell:Sendable { public var tank=ProcessTank(); public var valve=ControlValve(); public var pid=PIDController(kp:2,ki:0.25,kd:0); public var setpoint=60.0; public init(){}; public mutating func step(dt:Double)->Double{let command=pid.step(setpoint:setpoint,pv:tank.levelPercent,dt:dt);valve.commandPercent=command;valve.step(dt:dt);tank.inletLPS=valve.actualPercent/100*8;tank.outletLPS=4;tank.step(dt:dt);return command} }

// MARK: - Network timing and stale data
public struct NetworkValue:Sendable,Codable,Equatable { public var value:Double; public var timestamp:Double; public var qualityGood:Bool; public init(_ value:Double,timestamp:Double,qualityGood:Bool=true){self.value=value;self.timestamp=timestamp;self.qualityGood=qualityGood} }
public enum DataQuality:String,Sendable,Codable { case good, stale, bad }
public enum NetworkDiagnostics { public static func quality(_ value:NetworkValue,now:Double,maxAge:Double)->DataQuality { if !value.qualityGood{return .bad}; return now-value.timestamp>maxAge ? .stale:.good } }

// MARK: - Integrated Rev10 engineering plant
public struct Rev10EngineeringPlant:Sendable { public var rev9=Rev9AutomationPlant(); public var enclosure=PanelEnclosure(); public var accessories:[PanelAccessory]=[]; public var builtWires:[BuiltConductor]=[]; public var advancedPLC=AdvancedAutomationRuntime(); public var levelCell=ClosedLoopLevelCell(); public init(){}; public var workmanshipValid:Bool{builtWires.allSatisfy(\.buildValid)} }
