import Foundation

// Rev24 — Spatial cabinet authoring, wire routing, terminal/gland identity, and documentation projection.
// Geometry and separation checks are educational engineering heuristics, not code/standard compliance declarations.

public enum CabinetSurface: String, Sendable, Codable { case backplate, door, sidewall, bottomPlate }
public enum MountingKind: String, Sendable, Codable { case dinRail, backplate, doorCutout, wireDuct, busbar, glandPlate }
public struct CabinetPoint: Sendable, Codable, Hashable { public var x:Double; public var y:Double; public init(_ x:Double,_ y:Double){self.x=x;self.y=y} }
public struct SpatialDINRail: Sendable, Codable, Hashable { public var id:String; public var origin:CabinetPoint; public var lengthMM:Double; public var occupied:[PanelRect]; public init(id:String,origin:CabinetPoint,lengthMM:Double){self.id=id;self.origin=origin;self.lengthMM=lengthMM;self.occupied=[]}
    public mutating func mount(widthMM:Double,atX x:Double,heightMM:Double=60)->Bool { let r=PanelRect(origin.x+x,origin.y,widthMM,heightMM); guard x>=0 && x+widthMM<=lengthMM && !occupied.contains(where:{$0.intersects(r)}) else{return false}; occupied.append(r); return true }
}
public enum DuctClass:String,Sendable,Codable { case power, control, analog, network, mixed }
public struct WireDuctRoute:Sendable,Codable,Hashable { public var id:String; public var rect:PanelRect; public var ductClass:DuctClass; public var capacityAreaMM2:Double; public var usedAreaMM2:Double; public init(id:String,rect:PanelRect,ductClass:DuctClass,capacityAreaMM2:Double=1000,usedAreaMM2:Double=0){self.id=id;self.rect=rect;self.ductClass=ductClass;self.capacityAreaMM2=capacityAreaMM2;self.usedAreaMM2=usedAreaMM2}; public var fillFraction:Double{capacityAreaMM2 > 0 ? usedAreaMM2/capacityAreaMM2 : 1} }
public enum TerminalFunction:String,Sendable,Codable { case feedThrough, fused, disconnect, ground, shield, thermocouple, analog, discrete, network, power }
public struct SpatialTerminal:Sendable,Codable,Hashable { public var id:String; public var deviceTag:String; public var number:String; public var function:TerminalFunction; public var position:CabinetPoint; public var railID:String?; public init(id:String,deviceTag:String,number:String,function:TerminalFunction,position:CabinetPoint,railID:String?=nil){self.id=id;self.deviceTag=deviceTag;self.number=number;self.function=function;self.position=position;self.railID=railID} }
public struct CableGland:Sendable,Codable,Hashable { public var id:String; public var cableTag:String; public var position:CabinetPoint; public var sealed:Bool; public var waterIngressRisk:Double; public init(id:String,cableTag:String,position:CabinetPoint,sealed:Bool=true,waterIngressRisk:Double=0){self.id=id;self.cableTag=cableTag;self.position=position;self.sealed=sealed;self.waterIngressRisk=waterIngressRisk} }
public struct DoorDevice:Sendable,Codable,Hashable { public enum Kind:String,Sendable,Codable { case hmi, selector, pushbutton, pilotLight, estop, disconnectHandle, meter, annunciator }; public var tag:String; public var kind:Kind; public var rect:PanelRect; public init(tag:String,kind:Kind,rect:PanelRect){self.tag=tag;self.kind=kind;self.rect=rect} }
public struct SpatialWire:Sendable,Codable,Hashable { public var wireNumber:String; public var fromTerminal:String; public var toTerminal:String; public var signalClass:DuctClass; public var points:[CabinetPoint]; public var areaMM2:Double; public init(wireNumber:String,from:String,to:String,signalClass:DuctClass,points:[CabinetPoint]=[],areaMM2:Double=4){self.wireNumber=wireNumber;self.fromTerminal=from;self.toTerminal=to;self.signalClass=signalClass;self.points=points;self.areaMM2=areaMM2}; public var lengthMM:Double { guard points.count>1 else{return 0}; return zip(points,points.dropFirst()).reduce(0){$0 + hypot($1.1.x-$1.0.x,$1.1.y-$1.0.y)} } }

public struct SpatialCabinet:Sendable,Codable {
    public var id:String; public var widthMM:Double; public var heightMM:Double
    public var architecture:PanelArchitecture
    public var rails:[SpatialDINRail]=[]; public var ducts:[WireDuctRoute]=[]; public var terminals:[String:SpatialTerminal]=[:]; public var glands:[CableGland]=[]; public var door:[DoorDevice]=[]; public var wires:[SpatialWire]=[]
    public init(id:String,widthMM:Double=1000,heightMM:Double=1800,architecture:PanelArchitecture=PanelArchitecture()){self.id=id;self.widthMM=widthMM;self.heightMM=heightMM;self.architecture=architecture}
    public mutating func addTerminal(_ t:SpatialTerminal){terminals[t.id]=t}
    public mutating func routeWire(number:String,from:String,to:String,class signalClass:DuctClass,areaMM2:Double=4)->Bool { guard let a=terminals[from],let b=terminals[to] else{return false}; let midX=(a.position.x+b.position.x)/2; let pts=[a.position,CabinetPoint(midX,a.position.y),CabinetPoint(midX,b.position.y),b.position]; wires.append(.init(wireNumber:number,from:from,to:to,signalClass:signalClass,points:pts,areaMM2:areaMM2)); return true }
    public var audit:[String] { var a=architecture.audit; for d in ducts where d.fillFraction>0.8 {a.append("duct fill high: \(d.id)")}; let nums=Dictionary(grouping:wires,by:{$0.wireNumber}); for (n,x) in nums where x.count>1 {a.append("duplicate wire number: \(n)")}; for g in glands where !g.sealed || g.waterIngressRisk>0.5 {a.append("gland environmental risk: \(g.id)")}; for x in door.indices {for y in door.indices where y>x && door[x].rect.intersects(door[y].rect){a.append("door devices overlap: \(door[x].tag) / \(door[y].tag)")}}; return a }
    public func continuityPath(from terminalID:String)->[String] { var q=[terminalID], seen:Set<String>=[]; while !q.isEmpty {let x=q.removeFirst(); guard seen.insert(x).inserted else{continue}; for w in wires {if w.fromTerminal==x && !seen.contains(w.toTerminal){q.append(w.toTerminal)}; if w.toTerminal==x && !seen.contains(w.fromTerminal){q.append(w.fromTerminal)}}}; return Array(seen).sorted() }
}

public struct CabinetTemplateFactory {
    public static func compressorControlSpatial()->SpatialCabinet { var c=SpatialCabinet(id:"UCP-1",architecture:.init(widthMM:1000,heightMM:1800,components:PanelTemplateFactory.compressorUnitControl().components)); c.rails=[.init(id:"DR-1",origin:.init(250,280),lengthMM:680),.init(id:"DR-2",origin:.init(250,620),lengthMM:680),.init(id:"DR-3",origin:.init(80,1380),lengthMM:820)]; c.ducts=[.init(id:"WD-PWR",rect:.init(25,40,60,1250),ductClass:.power),.init(id:"WD-CTRL",rect:.init(210,250,55,1000),ductClass:.control),.init(id:"WD-SIG",rect:.init(930,250,45,1000),ductClass:.analog)]; c.door=[.init(tag:"HMI-1",kind:.hmi,rect:.init(300,250,400,280)),.init(tag:"ES-1",kind:.estop,rect:.init(100,650,80,80)),.init(tag:"DS-HDL",kind:.disconnectHandle,rect:.init(100,250,100,180))]; c.addTerminal(.init(id:"TB1:1",deviceTag:"TB1",number:"1",function:.analog,position:.init(200,1450),railID:"DR-3")); c.addTerminal(.init(id:"MX5:AI1+",deviceTag:"MX5-1",number:"AI1+",function:.analog,position:.init(580,620),railID:"DR-2")); _=c.routeWire(number:"401+",from:"TB1:1",to:"MX5:AI1+",class:.analog); c.glands=[.init(id:"G-401",cableTag:"CBL-401",position:.init(200,1760))]; return c }
    public static func burnerSpatial()->SpatialCabinet { var c=SpatialCabinet(id:"BMS-1",widthMM:800,heightMM:1400,architecture:PanelTemplateFactory.burnerPanel()); c.rails=[.init(id:"DR-B1",origin:.init(210,330),lengthMM:500),.init(id:"DR-B2",origin:.init(70,1040),lengthMM:650)]; c.ducts=[.init(id:"WD-BCTRL",rect:.init(190,300,45,650),ductClass:.control),.init(id:"WD-BFIELD",rect:.init(710,300,45,650),ductClass:.control)]; c.addTerminal(.init(id:"BMS:PILOT",deviceTag:"BMS-1",number:"PILOT",function:.discrete,position:.init(500,380),railID:"DR-B1")); c.addTerminal(.init(id:"TB-B:1",deviceTag:"TB-BURNER",number:"1",function:.discrete,position:.init(200,1080),railID:"DR-B2")); _=c.routeWire(number:"PIL-24",from:"BMS:PILOT",to:"TB-B:1",class:.control); c.glands=[.init(id:"G-PIL",cableTag:"CBL-PILOT",position:.init(200,1360))]; return c }
}

public struct DocumentationProjection:Sendable,Codable { public var wireSchedule:[String]; public var terminalPlan:[String]; public var glandSchedule:[String]; public init(cabinet:SpatialCabinet){wireSchedule=cabinet.wires.map{"\($0.wireNumber): \($0.fromTerminal) -> \($0.toTerminal), \(Int($0.lengthMM)) mm"}.sorted();terminalPlan=cabinet.terminals.values.map{"\($0.id) [\($0.function.rawValue)]"}.sorted();glandSchedule=cabinet.glands.map{"\($0.id): \($0.cableTag)"}.sorted()} }
