import Foundation

public struct EECompressorCylinder: Sendable, Codable, Equatable { public var id:String; public var suctionValveHealth=1.0; public var dischargeValveHealth=1.0; public var rodDropMM=0.0; public var peakVibration=0.12; public var dischargeTempC=75.0; public var capacity=1.0; public init(id:String){self.id=id}; public mutating func tick(load:Double,dt:Double){let leak=(2-suctionValveHealth-dischargeValveHealth)*0.5;capacity=max(0.2,load*(1-leak*0.5));peakVibration += ((0.1+leak*0.8+abs(rodDropMM)*0.25)-peakVibration)*min(1,dt/8);dischargeTempC += ((68+load*18+leak*35)-dischargeTempC)*min(1,dt/20)} }
public struct EERecipCompressorTrain: Sendable, Codable, Equatable { public var cylinders=[EECompressorCylinder(id:"CYL-1"),EECompressorCylinder(id:"CYL-2")]; public var crankRPM=900.0; public var frameVibration=0.12; public init(){}; public mutating func tick(load:Double,dt:Double){for i in cylinders.indices{cylinders[i].tick(load:load,dt:dt)};frameVibration=cylinders.map(\.peakVibration).max() ?? 0} }

public struct EESeparatorDynamics:Sendable,Codable,Equatable { public var liquidLevelPercent=32.0; public var inletLiquidRate=0.08; public var dumpValvePercent=18.0; public var carryoverRisk=0.0; public init(){}; public mutating func tick(dt:Double){let dump=dumpValvePercent/100*0.12;liquidLevelPercent=max(0,min(100,liquidLevelPercent+(inletLiquidRate-dump)*dt));carryoverRisk=max(0,min(1,(liquidLevelPercent-75)/20))} }
public struct EECoolerDynamics:Sendable,Codable,Equatable { public var fouling=0.08; public var fanAvailable=true; public var outletTempC=38.0; public init(){}; public mutating func tick(inletC:Double,ambientC:Double,dt:Double){let effectiveness=(fanAvailable ? 0.72:0.18)*(1-min(0.8,fouling));let target=inletC-(inletC-ambientC)*effectiveness;outletTempC += (target-outletTempC)*min(1,dt/25)} }
public struct EERecycleValveDynamics:Sendable,Codable,Equatable { public var command=3.0; public var travel=3.0; public var stiction=0.02; public var airLeak=0.0; public var strokeSeconds=1.5; public init(){}; public mutating func tick(dt:Double,airPSI:Double){let authority=max(0,min(1,(airPSI-20)/80))*(1-airLeak);let error=command-travel;if abs(error)>stiction*100 {let maxStep=100/max(0.2,strokeSeconds)*dt*authority;travel += max(-maxStep,min(maxStep,error))};travel=max(0,min(100,travel))} }

public enum EEProtectionFunction:String,CaseIterable,Sendable,Codable { case overload, shortCircuit, groundFault, underVoltage, overTemperature, phaseLoss }
public struct EEProtectionDevice:Sendable,Codable,Equatable { public var id:String; public var functions:Set<EEProtectionFunction>; public var pickupAmps:Double; public var delaySeconds:Double; public var accumulated=0.0; public var tripped=false; public init(id:String,functions:Set<EEProtectionFunction>,pickupAmps:Double,delaySeconds:Double){self.id=id;self.functions=functions;self.pickupAmps=pickupAmps;self.delaySeconds=delaySeconds}; public mutating func evaluate(amps:Double,dt:Double){if amps>pickupAmps {accumulated += dt}else{accumulated=max(0,accumulated-dt*2)};if accumulated>=delaySeconds{tripped=true}} }
public struct EEControlPowerSystem:Sendable,Codable,Equatable { public var dcBus=24.2; public var batterySOC=1.0; public var chargerAvailable=true; public var loadAmps=4.0; public init(){}; public mutating func tick(dt:Double){if chargerAvailable{batterySOC=min(1,batterySOC+dt/7200);dcBus=24.2}else{batterySOC=max(0,batterySOC-loadAmps*dt/180000);dcBus=20.0+4.0*batterySOC}} }

public enum EEIOModuleHealth:String,CaseIterable,Sendable,Codable {case healthy, channelFault, fieldPowerLost, networkLost, moduleFault}
public struct EEIOModule:Sendable,Codable,Equatable { public var id:String; public var slot:Int; public var health:EEIOModuleHealth = .healthy; public var channels:Int; public var diagnostics:[String]=[]; public init(id:String,slot:Int,channels:Int){self.id=id;self.slot=slot;self.channels=channels}; public mutating func diagnose(){diagnostics=[];if health != .healthy{diagnostics.append(health.rawValue)}} }
public struct EEPLCRack:Sendable,Codable,Equatable { public var id="PLC-1"; public var controllerHealthy=true; public var modules=[EEIOModule(id:"AI-2",slot:2,channels:8),EEIOModule(id:"AO-3",slot:3,channels:4),EEIOModule(id:"DI-4",slot:4,channels:16)]; public init(){}; public var healthy:Bool{controllerHealthy && modules.allSatisfy{$0.health == .healthy}} }

public enum EENetworkProtocol:String,CaseIterable,Sendable,Codable {case ethernetIP, modbusTCP, serial, can}
public struct EENetworkLink:Sendable,Codable,Equatable { public var id:String; public var protocolType:EENetworkProtocol; public var latencyMS=2.0; public var packetLoss=0.0; public var noise=0.0; public var up=true; public init(id:String,protocolType:EENetworkProtocol){self.id=id;self.protocolType=protocolType}; public var quality:Double{up ? max(0,1-packetLoss-noise*0.5):0} }
public struct EEHistorianConfig:Sendable,Codable,Equatable { public var deadband=0.2; public var compression=true; public var maxGapSeconds=30.0; public init(){}; public func shouldStore(previous:Double,new:Double,elapsed:Double)->Bool{!compression || abs(new-previous)>=deadband || elapsed>=maxGapSeconds} }

public struct EEAlarmPolicy:Sendable,Codable,Equatable { public var shelved:Set<String>=[]; public var suppressed:Set<String>=[]; public var firstOut:String?; public init(){}; public mutating func observe(_ alarm:EELiveAlarm){guard alarm.active,!shelved.contains(alarm.id),!suppressed.contains(alarm.id) else{return};if firstOut == nil{firstOut=alarm.id}}; public mutating func resetFirstOut(){firstOut=nil} }
public struct EECalibrationDrift:Sendable,Codable,Equatable { public var identity:String; public var biasPercent=0.0; public var driftPerHour=0.002; public init(identity:String){self.identity=identity}; public mutating func tick(hours:Double){biasPercent += driftPerHour*hours}; public mutating func calibrate(){biasPercent=0} }
public struct EEBacklog:Sendable,Codable,Equatable { public var open:[EEMaintenanceTask]=[]; public init(){}; public var overdueCount:Int{open.filter{!$0.completed}.count} }
public struct EEInspectionRoute:Sendable,Codable,Equatable { public var id:String; public var checkpoints:[String]; public var completed:Set<String>=[]; public init(id:String,checkpoints:[String]){self.id=id;self.checkpoints=checkpoints}; public var progress:Double{checkpoints.isEmpty ? 1 : Double(completed.count)/Double(checkpoints.count)} }
public struct EESparePart:Sendable,Codable,Equatable { public var sku:String; public var onHand:Int; public var reorderPoint:Int; public var leadDays:Int; public init(_ sku:String,_ onHand:Int,_ reorderPoint:Int,_ leadDays:Int){self.sku=sku;self.onHand=onHand;self.reorderPoint=reorderPoint;self.leadDays=leadDays}; public var needsReorder:Bool{onHand<=reorderPoint} }

public struct EECauseEffectRow:Sendable,Codable,Equatable { public var cause:String; public var actions:[String]; public var latched:Bool; public var firstOutEligible:Bool; public init(cause:String,actions:[String],latched:Bool=true,firstOutEligible:Bool=true){self.cause=cause;self.actions=actions;self.latched=latched;self.firstOutEligible=firstOutEligible} }
public struct EECauseEffectMatrix:Sendable,Codable,Equatable { public var rows=[EECauseEffectRow(cause:"surge detected",actions:["open ASV-401","trip COMP-2"]),EECauseEffectRow(cause:"VFD feeder open",actions:["trip COMP-2","alarm MCC-2"]),EECauseEffectRow(cause:"instrument air low",actions:["alarm IA-HDR","drive fail-safe actions"])]; public init(){}; public func actions(for causes:[String])->[String]{rows.filter{causes.contains($0.cause)}.flatMap(\.actions)} }

public struct EEIntegratedPlantRev39:Sendable,Codable,Equatable {
 public var base=EECausalFacilitySimulation(); public var recip=EERecipCompressorTrain(); public var separator=EESeparatorDynamics(); public var cooler=EECoolerDynamics(); public var recycle=EERecycleValveDynamics(); public var motorProtection=EEProtectionDevice(id:"MPR-2",functions:[.overload,.phaseLoss],pickupAmps:125,delaySeconds:4); public var controlPower=EEControlPowerSystem(); public var plc=EEPLCRack(); public var networks=[EENetworkLink(id:"ENET-PLC-VFD",protocolType:.ethernetIP),EENetworkLink(id:"SERIAL-BMS",protocolType:.serial),EENetworkLink(id:"CAN-AUX",protocolType:.can)]; public var historian=EEHistorianConfig(); public var alarmPolicy=EEAlarmPolicy(); public var drift=EECalibrationDrift(identity:"PIT-401"); public var backlog=EEBacklog(); public var route=EEInspectionRoute(id:"ROUTE-A",checkpoints:["MCC-2","COMP-2","SEP-101","ASV-401","IA-HDR"]); public var spares=[EESparePart("TERM-DISC",3,2,2),EESparePart("RELAY-24V",5,2,1),EESparePart("AI-MODULE",1,1,5)]; public var causeEffect=EECauseEffectMatrix(); public init(){}
 public mutating func tick(seconds:Double){base.tick(seconds:seconds);var left=max(0,seconds);while left>0{let dt=min(0.25,left);let load=max(0.1,min(1,base.unit.rpm/1250));recip.tick(load:load,dt:dt);separator.tick(dt:dt);cooler.tick(inletC:base.unit.bearingTempC+30,ambientC:base.living.weather.ambientC,dt:dt);recycle.command=base.unit.recyclePercent;recycle.tick(dt:dt,airPSI:base.instrumentAir.headerPSI);base.unit.recyclePercent=recycle.travel;motorProtection.evaluate(amps:base.power.vfd.amps,dt:dt);if motorProtection.tripped{base.power.vfd.breakerClosed=false};controlPower.tick(dt:dt);drift.tick(hours:dt/3600);left-=dt};for i in base.automation.channels.indices where base.automation.channels[i].tag=="PIT401_PV"{base.automation.channels[i].value *= 1+drift.biasPercent/100};backlog.open=base.maintenance.due}
 public var protectionActions:[String]{causeEffect.actions(for:base.esd.causes)}
}
