import Foundation

public enum EEProcessEquipmentKind:String,CaseIterable,Sendable,Codable { case suctionHeader, separator, compressor, cooler, recycleValve, dischargeHeader, dehydrator, tank, flare }
public struct EEProcessEquipment:Sendable,Codable,Equatable { public var id:String; public var kind:EEProcessEquipmentKind; public var pressurePSI:Double; public var temperatureC:Double; public var flow:Double; public var level:Double; public var running:Bool; public init(id:String,kind:EEProcessEquipmentKind,pressurePSI:Double=0,temperatureC:Double=24,flow:Double=0,level:Double=0,running:Bool=true){self.id=id;self.kind=kind;self.pressurePSI=pressurePSI;self.temperatureC=temperatureC;self.flow=flow;self.level=level;self.running=running} }

public struct EECompressorUnit:Sendable,Codable,Equatable { public var id:String; public var suctionPSI=85.0; public var dischargePSI=150.0; public var rpm=1050.0; public var flow=100.0; public var recyclePercent=3.0; public var surgeMargin=0.35; public var vibration=0.18; public var bearingTempC=58.0; public var loaded=true; public init(id:String){self.id=id}; public mutating func tick(dt:Double,load:Double){ let targetRPM=loaded ? 900 + 350*load : 700; rpm += (targetRPM-rpm)*min(1,dt/6); flow=max(5,100*load + recyclePercent*0.5); dischargePSI += ((suctionPSI + rpm*0.062)-dischargePSI)*min(1,dt/10); surgeMargin=max(-0.2,min(1,(flow/100)-0.42 + recyclePercent/120)); bearingTempC += ((38 + rpm*0.018 + vibration*10)-bearingTempC)*min(1,dt/30) } }
public struct EEAntiSurgeController:Sendable,Codable,Equatable { public var controlLine=0.18; public var emergencyLine=0.06; public var commandPercent=3.0; public var trip=false; public init(){}; public mutating func update(margin:Double,dt:Double)->Double { if margin <= emergencyLine {commandPercent=100;trip=true} else if margin < controlLine {commandPercent=min(100,commandPercent + 55*dt)} else {commandPercent=max(2,commandPercent-8*dt);trip=false}; return commandPercent } }

public struct EEPowerFeeder:Sendable,Codable,Equatable { public var id:String; public var volts:Double; public var amps:Double; public var breakerClosed:Bool; public var temperatureC:Double; public init(id:String,volts:Double=480,amps:Double=0,breakerClosed:Bool=true,temperatureC:Double=30){self.id=id;self.volts=volts;self.amps=amps;self.breakerClosed=breakerClosed;self.temperatureC=temperatureC}; public mutating func tick(dt:Double){let target=25 + amps*0.09;temperatureC += (target-temperatureC)*min(1,dt/90)} }
public struct EEPowerDistribution:Sendable,Codable,Equatable { public var main=EEPowerFeeder(id:"SWGR-MAIN",amps:185); public var mcc=EEPowerFeeder(id:"MCC-2",amps:120); public var vfd=EEPowerFeeder(id:"VFD-2",amps:92); public var control24V=24.1; public init(){}; public mutating func tick(dt:Double,compressorRPM:Double){vfd.amps=vfd.breakerClosed ? max(0,compressorRPM/12):0;mcc.amps=vfd.amps+22;main.amps=mcc.amps+65;main.tick(dt:dt);mcc.tick(dt:dt);vfd.tick(dt:dt)} }

public struct EEInstrumentAirSystem:Sendable,Codable,Equatable { public var headerPSI=100.0; public var dryerDewPointC = -35.0; public var leakRate=0.02; public var compressorAvailable=true; public init(){}; public mutating func tick(dt:Double){let target=compressorAvailable ? 100.0 : 0;headerPSI += (target-headerPSI)*min(1,dt/45);headerPSI=max(0,headerPSI-leakRate*dt)} }
public struct EEIOChannel:Sendable,Codable,Equatable { public var rack:String; public var slot:Int; public var channel:Int; public var tag:String; public var value:Double; public var quality:Double; public init(_ rack:String,_ slot:Int,_ channel:Int,_ tag:String,_ value:Double,_ quality:Double=1){self.rack=rack;self.slot=slot;self.channel=channel;self.tag=tag;self.value=value;self.quality=quality} }
public struct EEAutomationPlant:Sendable,Codable,Equatable { public var channels:[EEIOChannel]=[.init("RIO-1",2,0,"PIT401_PV",150.0),.init("RIO-1",2,1,"FIT401_PV",100),.init("RIO-1",3,0,"ASV401_FB",3)]; public var plcScanMS=20.0; public var networkHealth=1.0; public init(){}; public mutating func update(unit:EECompressorUnit){ if let i=channels.firstIndex(where:{$0.tag=="PIT401_PV"}){channels[i].value=unit.dischargePSI};if let i=channels.firstIndex(where:{$0.tag=="FIT401_PV"}){channels[i].value=unit.flow};if let i=channels.firstIndex(where:{$0.tag=="ASV401_FB"}){channels[i].value=unit.recyclePercent} } }

public enum EEESDLevel:Int,CaseIterable,Sendable,Codable { case normal=0, unitTrip=1, processArea=2, station=3 }
public struct EEESDSystem:Sendable,Codable,Equatable { public var level:EEESDLevel = .normal; public var causes:[String]=[]; public init(){}; public mutating func evaluate(unit:EECompressorUnit,power:EEPowerDistribution,air:EEInstrumentAirSystem){ causes=[]; if unit.surgeMargin < 0 {causes.append("surge detected")};if unit.bearingTempC>95{causes.append("bearing temperature")};if !power.vfd.breakerClosed{causes.append("VFD feeder open")};if air.headerPSI<55{causes.append("instrument air low")}; level = causes.isEmpty ? .normal : .unitTrip } }

public enum EEMaintenanceKind:String,CaseIterable,Sendable,Codable { case inspection, preventive, predictive, calibration }
public struct EEMaintenanceTask:Sendable,Codable,Equatable { public var id:String; public var identity:String; public var kind:EEMaintenanceKind; public var dueHours:Double; public var conditionScore:Double; public var completed=false; public init(id:String,identity:String,kind:EEMaintenanceKind,dueHours:Double,conditionScore:Double=1){self.id=id;self.identity=identity;self.kind=kind;self.dueHours=dueHours;self.conditionScore=conditionScore} }
public struct EEMaintenancePlanner:Sendable,Codable,Equatable { public var runtimeHours=0.0; public var tasks:[EEMaintenanceTask]=[.init(id:"PM-COMP2",identity:"COMP-2",kind:.preventive,dueHours:500),.init(id:"PDM-MCC2",identity:"MCC-2",kind:.predictive,dueHours:100,conditionScore:0.8),.init(id:"CAL-PIT401",identity:"PIT-401",kind:.calibration,dueHours:365)]; public init(){}; public mutating func tick(dt:Double){runtimeHours += dt/3600}; public var due:[EEMaintenanceTask]{tasks.filter{!$0.completed && ($0.dueHours <= runtimeHours || $0.conditionScore < 0.35)}} }

public struct EEAlarmRationalization:Sendable,Codable,Equatable { public var standingLimit=8; public var floodThresholdPerMinute=10; public init(){}; public func priority(_ alarm:EELiveAlarm)->Int {alarm.severity.rawValue*100 + (alarm.active ? 10:0)}; public func flood(_ alarms:[EELiveAlarm],now:Double)->Bool {alarms.filter{$0.firstSeen >= now-60}.count >= floodThresholdPerMinute} }
public struct EEMultiFaultIncident:Sendable,Codable,Equatable { public var id:String; public var rootFaults:[String]; public var consequences:[String]; public var active=true; public init(id:String,rootFaults:[String],consequences:[String]){self.id=id;self.rootFaults=rootFaults;self.consequences=consequences} }
public struct EEProceduralCase:Sendable,Codable,Equatable { public var id:String; public var symptom:String; public var identities:[String]; public var hiddenFaults:[String]; public var requiredEvidence:[String]; public init(id:String,symptom:String,identities:[String],hiddenFaults:[String],requiredEvidence:[String]){self.id=id;self.symptom=symptom;self.identities=identities;self.hiddenFaults=hiddenFaults;self.requiredEvidence=requiredEvidence} }
public struct EEProceduralCaseGenerator:Sendable { public init(){}; public func generate(station:EECausalFacilitySimulation)->[EEProceduralCase]{ var cases:[EEProceduralCase]=[]; if station.unit.surgeMargin < 0.15 {cases.append(.init(id:"CASE-SURGE",symptom:"Compressor operating near surge",identities:[station.unit.id,"ASV-401","FIT-401"],hiddenFaults:["low flow or recycle response"],requiredEvidence:["flow trend","recycle travel","surge margin"]))}; if station.power.mcc.temperatureC>55 {cases.append(.init(id:"CASE-MCC",symptom:"MCC thermal anomaly",identities:["MCC-2"],hiddenFaults:["connection resistance or overload"],requiredEvidence:["thermal image","load current","de-energized inspection"]))}; if station.instrumentAir.headerPSI<75 {cases.append(.init(id:"CASE-AIR",symptom:"Instrument air pressure low",identities:["IA-HDR","ASV-401"],hiddenFaults:["leak or compressor unavailable"],requiredEvidence:["header pressure","leak inspection"]))}; return cases } }

public struct EECausalFacilitySimulation:Sendable,Codable,Equatable {
 public var living=EELivingCompressorStation(); public var equipment:[EEProcessEquipment]=[.init(id:"SUCT-HDR",kind:.suctionHeader,pressurePSI:85,flow:100),.init(id:"SEP-101",kind:.separator,pressurePSI:84,flow:100,level:35),.init(id:"COMP-2",kind:.compressor,pressurePSI:150,temperatureC:58,flow:100),.init(id:"CLR-2",kind:.cooler,pressurePSI:147,temperatureC:38,flow:100),.init(id:"ASV-401",kind:.recycleValve,pressurePSI:147,flow:3),.init(id:"DISCH-HDR",kind:.dischargeHeader,pressurePSI:145,flow:97),.init(id:"DEHY-1",kind:.dehydrator,pressurePSI:142,flow:96),.init(id:"TANK-1",kind:.tank,level:42),.init(id:"FLARE-1",kind:.flare,running:false)]; public var unit=EECompressorUnit(id:"COMP-2"); public var antiSurge=EEAntiSurgeController(); public var power=EEPowerDistribution(); public var instrumentAir=EEInstrumentAirSystem(); public var automation=EEAutomationPlant(); public var esd=EEESDSystem(); public var maintenance=EEMaintenancePlanner(); public var incidents:[EEMultiFaultIncident]=[]; public var generatedCases:[EEProceduralCase]=[]
 public init(){}
 public mutating func tick(seconds:Double){var left=max(0,seconds);while left>0{let dt=min(0.25,left);let load=max(0.05,min(1,(living.pid.output-700)/700));unit.recyclePercent=antiSurge.update(margin:unit.surgeMargin,dt:dt);unit.tick(dt:dt,load:load);power.tick(dt:dt,compressorRPM:unit.rpm);instrumentAir.tick(dt:dt);automation.update(unit:unit);esd.evaluate(unit:unit,power:power,air:instrumentAir);maintenance.tick(dt:dt);left-=dt}; living.process.suctionPSI=unit.suctionPSI;living.process.dischargePSI=unit.dischargePSI;living.process.rpm=unit.rpm;living.process.valveCommand=unit.recyclePercent;living.process.valveTravel=unit.recyclePercent;living.tick(seconds:seconds);syncEquipment();generatedCases=EEProceduralCaseGenerator().generate(station:self)}
 mutating func syncEquipment(){for i in equipment.indices {switch equipment[i].id {case "COMP-2":equipment[i].pressurePSI=unit.dischargePSI;equipment[i].temperatureC=unit.bearingTempC;equipment[i].flow=unit.flow;case "ASV-401":equipment[i].flow=unit.recyclePercent;case "DISCH-HDR":equipment[i].pressurePSI=max(0,unit.dischargePSI-5);equipment[i].flow=max(0,unit.flow-unit.recyclePercent);default:break}}}
 public mutating func injectIncident(_ incident:EEMultiFaultIncident){incidents.append(incident);for f in incident.rootFaults {if f=="instrument-air-leak"{instrumentAir.leakRate=0.25};if f=="vfd-feeder-open"{power.vfd.breakerClosed=false};if f=="low-flow"{unit.flow=25;unit.surgeMargin=0.02}}}
}
