import Foundation

public enum EEFacilityZone:String,CaseIterable,Sendable,Codable { case controlRoom, compressorBuilding, mccRoom, dehydration, tankBattery, flare, instrumentShop, toolTruck }
public struct EEZoneLink:Sendable,Codable,Equatable { public var from:EEFacilityZone; public var to:EEFacilityZone; public var travelSeconds:Double; public init(_ from:EEFacilityZone,_ to:EEFacilityZone,_ travelSeconds:Double){self.from=from;self.to=to;self.travelSeconds=travelSeconds} }
public struct EEFacilityMap:Sendable,Codable,Equatable {
 public var links:[EEZoneLink] = [.init(.controlRoom,.compressorBuilding,75),.init(.controlRoom,.mccRoom,45),.init(.compressorBuilding,.dehydration,90),.init(.dehydration,.tankBattery,70),.init(.tankBattery,.flare,80),.init(.controlRoom,.instrumentShop,35),.init(.instrumentShop,.toolTruck,25)]
 public init(){}
 public func travelSeconds(from:EEFacilityZone,to:EEFacilityZone)->Double? { if from==to{return 0}; var frontier:[(EEFacilityZone,Double)]=[(from,0)]; var best:[EEFacilityZone:Double]=[from:0]; while !frontier.isEmpty { frontier.sort{$0.1<$1.1}; let (z,d)=frontier.removeFirst(); if z==to{return d}; for l in links { let n:EEFacilityZone? = l.from==z ? l.to : l.to==z ? l.from:nil; guard let n else{continue}; let nd=d+l.travelSeconds; if nd < best[n,default:.infinity] {best[n]=nd;frontier.append((n,nd))} } }; return nil }
}
public struct EEWeatherState:Sendable,Codable,Equatable { public var ambientC:Double=24; public var humidity:Double=0.55; public var rain:Double=0; public var windMPS:Double=2; public var lightningRisk:Double=0; public init(){}; public mutating func tick(seconds:Double){let phase=seconds/3600;ambientC += sin(phase)*0.01;humidity=min(1,max(0,humidity + rain*0.00002*seconds - 0.000002*seconds))} }
public struct EEProcessTrain:Sendable,Codable,Equatable { public var suctionPSI=85.0; public var dischargePSI=150.2; public var rpm=1050.0; public var valveCommand=52.0; public var valveTravel=51.5; public var vesselLevel=43.0; public var gasTempC=39.0; public init(){}; public mutating func tick(seconds:Double,speedCommand:Double){rpm += (speedCommand-rpm)*min(1,seconds/8); dischargePSI += ((90 + rpm*0.057)-dischargePSI)*min(1,seconds/12); gasTempC += ((24 + rpm*0.015)-gasTempC)*min(1,seconds/25); valveTravel += (valveCommand-valveTravel)*min(1,seconds/3)} }
public struct EEAutonomousPID:Sendable,Codable,Equatable { public var setpoint=150.0; public var kp=3.0; public var ki=0.08; public var integral=0.0; public var output=1050.0; public init(){}; public mutating func update(pv:Double,dt:Double)->Double { let e=setpoint-pv;integral=max(-300,min(300,integral+e*dt));output=max(700,min(1400,1050+kp*e+ki*integral));return output } }
public enum EEAlarmSeverity:Int,CaseIterable,Sendable,Codable { case advisory=1, warning=2, trip=3 }
public struct EELiveAlarm:Sendable,Codable,Equatable { public var id:String; public var identity:String; public var severity:EEAlarmSeverity; public var message:String; public var active:Bool; public var firstSeen:Double; public init(id:String,identity:String,severity:EEAlarmSeverity,message:String,active:Bool=true,firstSeen:Double){self.id=id;self.identity=identity;self.severity=severity;self.message=message;self.active=active;self.firstSeen=firstSeen} }
public enum EECallKind:String,Sendable,Codable { case operatorCall, radio, alarmDispatch, handoff }
public struct EEPlantCall:Sendable,Codable,Equatable { public var t:Double; public var kind:EECallKind; public var from:String; public var message:String; public var identity:String?; public init(t:Double,kind:EECallKind,from:String,message:String,identity:String?=nil){self.t=t;self.kind=kind;self.from=from;self.message=message;self.identity=identity} }
public struct EEIsolationPoint:Sendable,Codable,Equatable { public var id:String; public var identity:String; public var energy:String; public var isolated=false; public var verifiedZeroEnergy=false; public init(id:String,identity:String,energy:String){self.id=id;self.identity=identity;self.energy=energy} }
public struct EEPermit:Sendable,Codable,Equatable { public var id:String; public var equipment:String; public var requiredIsolationIDs:[String]; public var authorized=false; public init(id:String,equipment:String,requiredIsolationIDs:[String]){self.id=id;self.equipment=equipment;self.requiredIsolationIDs=requiredIsolationIDs} }
public struct EEIsolationBoard:Sendable,Codable,Equatable { public var points:[EEIsolationPoint]=[.init(id:"ISO-MCC2B",identity:"MCC-2B",energy:"480 VAC"),.init(id:"ISO-DVC201",identity:"DVC-201",energy:"instrument air")]; public var permits:[EEPermit]=[.init(id:"P-402",equipment:"MCC-2B",requiredIsolationIDs:["ISO-MCC2B"])]; public init(){}; public mutating func isolate(_ id:String,verify:Bool){guard let i=points.firstIndex(where:{$0.id==id}) else{return};points[i].isolated=true;points[i].verifiedZeroEnergy=verify}; public func ready(_ permit:EEPermit)->Bool { permit.requiredIsolationIDs.allSatisfy{id in points.first(where:{$0.id==id}).map{$0.isolated && $0.verifiedZeroEnergy} ?? false} } }
public struct EEInventoryItem:Sendable,Codable,Equatable { public var id:String; public var name:String; public var quantity:Int; public init(_ id:String,_ name:String,_ quantity:Int){self.id=id;self.name=name;self.quantity=quantity} }
public struct EEToolTruck:Sendable,Codable,Equatable { public var tools:Set<String>=["DMM","clamp meter","loop calibrator","thermal camera","insulation tester"]; public var inventory:[EEInventoryItem]=[.init("FUSE-2A","2 A control fuse",4),.init("FERRULE-18","18 AWG ferrule",40),.init("TERM-DISC","disconnect terminal",3),.init("RELAY-24","24 VDC relay",2)]; public init(){}; public mutating func consume(_ id:String)->Bool {guard let i=inventory.firstIndex(where:{$0.id==id && $0.quantity>0}) else{return false};inventory[i].quantity-=1;return true} }
public struct EEHandoff:Sendable,Codable,Equatable { public var t:Double; public var outgoing:String; public var summary:[String]; public var openWorkOrders:[String]; public init(t:Double,outgoing:String,summary:[String],openWorkOrders:[String]){self.t=t;self.outgoing=outgoing;self.summary=summary;self.openWorkOrders=openWorkOrders} }
public struct EEUnifiedCapture:Sendable,Codable,Equatable { public var t:Double; public var analog:[String:Double]; public var digital:[String:Bool]; public var alarms:[String]; public var packets:[EENetworkPacket]; public init(t:Double,analog:[String:Double],digital:[String:Bool],alarms:[String],packets:[EENetworkPacket]){self.t=t;self.analog=analog;self.digital=digital;self.alarms=alarms;self.packets=packets} }
public struct EEGeneratedWorkOrderRule:Sendable { public init(){}; public func generate(time:Double,assets:[EEDegradingAsset],alarms:[EELiveAlarm],existing:[EEShiftWorkOrder])->[EEShiftWorkOrder] { var out:[EEShiftWorkOrder]=[]; let ids=Set(existing.map{$0.identity}); for a in assets where a.temperatureC >= 70 && !ids.contains(a.identity) {out.append(.init(id:"AUTO-\(Int(time))-\(a.identity)",title:"Thermal anomaly detected",identity:a.identity,priority:.safety))}; for alarm in alarms where alarm.active && alarm.severity == .trip && !ids.contains(alarm.identity) {out.append(.init(id:"AUTO-ALM-\(Int(time))-\(alarm.identity)",title:alarm.message,identity:alarm.identity,priority:.production))}; return out } }

public struct EELivingCompressorStation:Sendable,Codable,Equatable {
 public var shift=EEPersistentShift(); public var map=EEFacilityMap(); public var zone:EEFacilityZone = .controlRoom; public var weather=EEWeatherState(); public var process=EEProcessTrain(); public var pid=EEAutonomousPID(); public var alarms:[EELiveAlarm]=[]; public var calls:[EEPlantCall]=[]; public var isolation=EEIsolationBoard(); public var truck=EEToolTruck(); public var captures:[EEUnifiedCapture]=[]; public var handoffs:[EEHandoff]=[]
 public init(){}
 public mutating func travel(to destination:EEFacilityZone){guard let seconds=map.travelSeconds(from:zone,to:destination) else{return};tick(seconds:seconds);zone=destination}
 public mutating func tick(seconds:Double){ let step=max(0.1,min(1,seconds)); var remaining=max(0,seconds); while remaining>0 {let dt=min(step,remaining);let cmd=pid.update(pv:process.dischargePSI,dt:dt);process.tick(seconds:dt,speedCommand:cmd);shift.tick(seconds:dt);weather.tick(seconds:dt);remaining-=dt}; evaluatePlant(); capture() }
 public mutating func evaluatePlant(){ let now=shift.time; for a in shift.assets { if a.temperatureC>=70 && !alarms.contains(where:{$0.id=="HOT-\(a.identity)"}) {alarms.append(.init(id:"HOT-\(a.identity)",identity:a.identity,severity:.warning,message:"High termination temperature",firstSeen:now));calls.append(.init(t:now,kind:.alarmDispatch,from:"SCADA",message:"Temperature warning at \(a.identity)",identity:a.identity))} }; if abs(process.dischargePSI-pid.setpoint)>12 && !alarms.contains(where:{$0.id=="PRESS-DEV"}) {alarms.append(.init(id:"PRESS-DEV",identity:"PIT-401",severity:.warning,message:"Discharge pressure deviation",firstSeen:now))}; let new=EEGeneratedWorkOrderRule().generate(time:now,assets:shift.assets,alarms:alarms,existing:shift.jobs);shift.jobs.append(contentsOf:new) }
 public mutating func capture(){captures.append(.init(t:shift.time,analog:["PIT-401":process.dischargePSI,"RPM":process.rpm,"MCC-2B_TEMP":shift.assets.first(where:{$0.identity=="MCC-2B"})?.temperatureC ?? 0],digital:["COMP_RUN":process.rpm>800],alarms:alarms.filter{$0.active}.map{$0.id},packets:[.init(t:shift.time,protocolName:"Modbus",source:"PLC",destination:"VFD",identifier:"speed",payload:[UInt8(clamping:Int(pid.output/10))],valid:true)])); if captures.count>720{captures.removeFirst(captures.count-720)} }
 public mutating func operatorCall(_ message:String,identity:String?=nil){calls.append(.init(t:shift.time,kind:.operatorCall,from:"Operator",message:message,identity:identity))}
 public mutating func createHandoff(outgoing:String)->EEHandoff { let h=EEHandoff(t:shift.time,outgoing:outgoing,summary:alarms.filter{$0.active}.map{$0.message},openWorkOrders:shift.jobs.filter{$0.state != .closed}.map{$0.id});handoffs.append(h);return h }
 public func encoded() throws->Data{try JSONEncoder().encode(self)}; public static func decoded(_ d:Data)throws->Self{try JSONDecoder().decode(Self.self,from:d)}
}
