import Foundation

public enum EEBenchExperimentKind:String,Sendable,Codable,CaseIterable { case dcOhms="DC & Ohm's Law", relay="Relay & Seal-In", rc="RC Transient", diode="Diode", motor="Motor Starter", fourToTwenty="4–20 mA Loop", plc="PLC I/O", vfd="VFD & Motor", network="Industrial Network", can="CAN Bus" }
public struct EEBenchNode:Identifiable,Sendable,Codable,Equatable { public var id:String; public var x:Double; public var y:Double; public var voltage:Double; public init(_ id:String,_ x:Double,_ y:Double,_ voltage:Double){self.id=id;self.x=x;self.y=y;self.voltage=voltage} }
public struct EEBenchLead:Sendable,Codable,Equatable { public var instrument:EEInstrumentKind; public var red:String?; public var black:String?; public init(instrument:EEInstrumentKind,red:String?=nil,black:String?=nil){self.instrument=instrument;self.red=red;self.black=black} }
public struct EEElectronicsBenchRev47:Sendable,Codable,Equatable {
 public var experiment:EEBenchExperimentKind = .dcOhms; public var supplyV=24.0; public var resistanceOhm=240.0; public var nodes:[EEBenchNode]=[.init("PS+",0.1,0.3,24),.init("LOAD+",0.45,0.3,24),.init("LOAD-",0.65,0.3,0),.init("PS-",0.9,0.3,0)]; public var lead=EEBenchLead(instrument:.dmm); public var evidence:[EEInstrumentEvidence]=[]; public init(){}
 public var currentA:Double { resistanceOhm > 0 ? supplyV/resistanceOhm : 0 }
 public mutating func placeRed(_ node:String){lead.red=node}; public mutating func placeBlack(_ node:String){lead.black=node}
 public mutating func measure(time:Double=0)->EEInstrumentEvidence?{guard let r=nodes.first(where:{$0.id==lead.red}),let b=nodes.first(where:{$0.id==lead.black}) else{return nil};let e=EEInstrumentEvidence(time:time,instrument:lead.instrument,identity:"BENCH:\(r.id)-\(b.id)",quantity:"Voltage",value:r.voltage-b.voltage,unit:"V",provenance:"simulation-truth");evidence.append(e);return e}
}

public enum EETrainingSchool:String,Sendable,Codable,CaseIterable { case fundamentals="Electrical Fundamentals", motor="Motor Controls", power="Industrial Power", instrumentation="Instrumentation", automation="PLC & Automation", drives="Drives", networks="Networks", process="Process Controls", diagnostics="Advanced Diagnostics", coal="Coal I&E", gas="Natural Gas I&E" }
public struct EETrainingLesson47:Identifiable,Sendable,Codable,Equatable { public var id:String; public var school:EETrainingSchool; public var title:String; public var instrument:EEInstrumentKind; public var objective:String; public var completed=false }
public struct EETrainingCenterRev47:Sendable,Codable,Equatable { public var lessons:[EETrainingLesson47]; public var xp=0; public init(){lessons=EETrainingSchool.allCases.enumerated().map{ i,s in .init(id:"TR-\(i+1)",school:s,title:"\(s.rawValue) Field Lab",instrument:[.dmm,.clampMeter,.phaseRotationMeter,.loopCalibrator,.oscilloscope,.networkAnalyzer,.vibrationAnalyzer,.processCalibrator,.thermalCamera,.insulationTester,.hartCommunicator][i],objective:"Observe, measure, diagnose, repair and prove the \(s.rawValue.lowercased()) system.")}}; public mutating func complete(_ id:String){guard let i=lessons.firstIndex(where:{$0.id==id}),!lessons[i].completed else{return};lessons[i].completed=true;xp += 100} }

public struct EEAssetLocation47:Identifiable,Sendable,Codable,Equatable { public var id:String; public var world:EEIndustrialWorld; public var zone:String; public var x:Double; public var y:Double; public var kind:String; public init(_ id:String,_ world:EEIndustrialWorld,_ zone:String,_ x:Double,_ y:Double,_ kind:String){self.id=id;self.world=world;self.zone=zone;self.x=x;self.y=y;self.kind=kind} }
public struct EESpatialWorldRev47:Sendable,Codable,Equatable { public var assets:[EEAssetLocation47]; public var selectedID:String?; public init(){assets=[
 .init("COMP-2",.naturalGas,"Compressor Building",0.48,0.48,"compressor"),.init("PIT-401",.naturalGas,"Discharge Header",0.64,0.43,"instrument"),.init("VFD-2",.naturalGas,"MCC Room",0.25,0.42,"drive"),.init("ASV-401",.naturalGas,"Recycle",0.58,0.28,"valve"),.init("SEP-101",.naturalGas,"Inlet",0.18,0.68,"separator"),.init("DEHY-1",.naturalGas,"Dehydration",0.78,0.62,"dehydrator"),
 .init("LW-NR",.coalMining,"North Ridge Longwall",0.15,0.22,"longwall"),.init("CV-NR-OL",.coalMining,"Overland Conveyor",0.34,0.36,"conveyor"),.init("ROM-NR-1",.coalMining,"Raw Storage",0.48,0.48,"silo"),.init("CPP-A-HMC",.coalMining,"Preparation Plant",0.62,0.49,"process"),.init("THK-101",.coalMining,"Water/Refuse",0.69,0.68,"thickener"),.init("TLO-WB-1",.coalMining,"Train Loadout",0.87,0.52,"loadout") ]}; public func assets(in world:EEIndustrialWorld)->[EEAssetLocation47]{assets.filter{$0.world==world}} }

public struct EEIdentityGraphRev47:Sendable,Codable,Equatable { public var identities:[EEUniversalIdentity]; public init(base:EEIdentityGraphRev46,spatial:EESpatialWorldRev47){var list=base.identities;for a in spatial.assets {if let i=list.firstIndex(where:{$0.id==a.id && $0.world==a.world}){if !list[i].bindings.contains(where:{$0.surface == .physical}){list[i].bindings.append(.init(.physical,"\(a.zone)/\(a.id)"))}} else {list.append(.init(id:a.id,world:a.world,bindings:[.init(.physical,"\(a.zone)/\(a.id)")]))}};identities=list.sorted{$0.id<$1.id} }; public func related(_ q:String)->[EEUniversalIdentity]{identities.filter{$0.id.localizedCaseInsensitiveContains(q)||$0.bindings.contains{$0.reference.localizedCaseInsensitiveContains(q)}}} }

public struct EEEvidenceCard47:Identifiable,Sendable,Codable,Equatable { public var id:String; public var time:Double; public var world:EEIndustrialWorld; public var identity:String; public var kind:EEObservationKind; public var statement:String; public var value:String; public var supports:Set<String>; public var contradicts:Set<String> }
public struct EEHypothesis47:Identifiable,Sendable,Codable,Equatable { public var id:String; public var title:String; public var domain:HypothesisDomain; public var probability:Double; public var confirmed=false; public var rejected=false }
public struct EEEvidenceBoardRev47:Sendable,Codable,Equatable {
 public var cards:[EEEvidenceCard47]=[]; public var hypotheses:[EEHypothesis47]=[
  .init(id:"H-WIRING",title:"Wiring / connection defect",domain:.wiring,probability:0.2),.init(id:"H-INST",title:"Instrumentation / measurement defect",domain:.instrumentation,probability:0.2),.init(id:"H-MECH",title:"Mechanical degradation",domain:.mechanical,probability:0.2),.init(id:"H-PROC",title:"Process condition",domain:.process,probability:0.2),.init(id:"H-CTRL",title:"Control / communications defect",domain:.logic,probability:0.2)]; public init(){}
 public mutating func ingest(_ card:EEEvidenceCard47){cards.append(card);for i in hypotheses.indices {if card.supports.contains(hypotheses[i].id){hypotheses[i].probability *= 1.8};if card.contradicts.contains(hypotheses[i].id){hypotheses[i].probability *= 0.25}};normalize()}
 public mutating func ingest(_ e:EEInstrumentEvidence,world:EEIndustrialWorld){ingest(.init(id:"E-\(cards.count+1)",time:e.time,world:world,identity:e.identity,kind:.measurement,statement:"\(e.quantity) measured with \(e.instrument.rawValue)",value:"\(e.value) \(e.unit)",supports:[],contradicts:[]))}
 public mutating func normalize(){let s=hypotheses.filter{!$0.rejected}.reduce(0){$0+$1.probability};guard s>0 else{return};for i in hypotheses.indices where !hypotheses[i].rejected {hypotheses[i].probability/=s}}
 public var ranked:[EEHypothesis47]{hypotheses.sorted{$0.probability>$1.probability}}
}

public struct EERev47DeepPlayableWorlds:Sendable,Codable,Equatable { public var base=EERev46PlayableIntegration(); public var bench=EEElectronicsBenchRev47(); public var training=EETrainingCenterRev47(); public var spatial=EESpatialWorldRev47(); public var board=EEEvidenceBoardRev47(); public init(){}; public var identities:EEIdentityGraphRev47{.init(base:base.identities,spatial:spatial)}; public mutating func capture(world:EEIndustrialWorld,channelID:String,instrument:EEInstrumentKind)->EEInstrumentEvidence?{base.instruments.selected=instrument;guard let snap=base.timeline.snapshots(for:world).last,let e=base.instruments.capture(snapshot:snap,channelID:channelID) else{return nil};board.ingest(e,world:world);return e} }
