import Foundation

// Rev42 deepens ONLY the coal/mining world. Natural-gas process models remain separate.
public enum EEMiningMethod:String,Sendable,Codable { case longwall, continuousMining }
public struct EELongwallSystem:Sendable,Codable,Equatable {
 public var shearerPositionM=40.0, faceLengthM=300.0, haulageMPS=0.12, cuttingMotorAmps=620.0
 public var afcLoadPercent=58.0, stageLoaderLoadPercent=52.0, crusherLoadPercent=45.0
 public var shieldPressureBar=310.0, shieldsAdvancedPercent=100.0, methanePercent=0.4
 public var running=true
 public init(){}
 public mutating func tick(dt:Double){guard running else{return}; shearerPositionM += haulageMPS*dt; if shearerPositionM>faceLengthM {shearerPositionM=0}; let hardness=max(0.5,min(1.5,cuttingMotorAmps/620)); afcLoadPercent=max(0,min(100,50+25*hardness));stageLoaderLoadPercent=max(0,min(100,afcLoadPercent*0.92));crusherLoadPercent=max(0,min(100,stageLoaderLoadPercent*0.88)) }
}
public struct EEContinuousSection:Sendable,Codable,Equatable { public var minerAmps=410.0, feederBreakerTPH=650.0, roofBolterAvailable=true, haulageAvailable=true, sectionBeltAvailable=true; public var productionTPH:Double { sectionBeltAvailable && haulageAvailable ? feederBreakerTPH : 0 }; public init(){} }
public enum EEUndergroundPowerHealth:String,Sendable,Codable { case healthy, groundFault, groundCheckOpen, undervoltage, breakerTrip }
public struct EEMinePowerCenter:Sendable,Codable,Equatable { public var id:String; public var primaryKV=12.47, secondaryV=995.0, feederAmps=420.0; public var groundMonitorHealthy=true, groundCheckHealthy=true; public var health:EEUndergroundPowerHealth { if !groundMonitorHealthy{return .groundFault};if !groundCheckHealthy{return .groundCheckOpen};if secondaryV<850{return .undervoltage};return .healthy }; public init(id:String){self.id=id} }

public struct EEBeltSafetyState:Sendable,Codable,Equatable { public var pullCord=false, misalignment=false, zeroSpeed=false, beltTear=false, coPPM=5.0, bearingC=38.0; public var permissive:Bool { !(pullCord || misalignment || zeroSpeed || beltTear || coPPM>50 || bearingC>90) }; public init(){} }
public struct EEUndergroundBelt:Sendable,Codable,Equatable { public var conveyor:EECoalConveyor; public var safety=EEBeltSafetyState(); public init(conveyor:EECoalConveyor){self.conveyor=conveyor}; public mutating func tick(dt:Double){ conveyor.running = safety.permissive; conveyor.tick(dt:dt); if conveyor.running { safety.bearingC += max(0,conveyor.motorAmps-150)*dt/20000 }; if safety.bearingC>80 { safety.coPPM += (safety.bearingC-80)*dt/100 } } }

public struct EEVentNode:Sendable,Codable,Equatable { public var id:String; public var pressureInWG:Double }
public struct EEVentBranch:Sendable,Codable,Equatable { public var id:String, from:String, to:String; public var resistance:Double; public var airflowCFM=0.0; public var regulatorPercent=100.0 }
public struct EEVentilationNetwork:Sendable,Codable,Equatable {
 public var nodes:[EEVentNode]=[.init(id:"INTAKE",pressureInWG:0),.init(id:"FACE",pressureInWG:-3),.init(id:"RETURN",pressureInWG:-7)]
 public var branches:[EEVentBranch]=[.init(id:"INTAKE-FACE",from:"INTAKE",to:"FACE",resistance:1.2),.init(id:"FACE-RETURN",from:"FACE",to:"RETURN",resistance:1.5)]
 public init(){}
 public mutating func solve(){let p=Dictionary(uniqueKeysWithValues:nodes.map{($0.id,$0.pressureInWG)});for i in branches.indices{let b=branches[i];let dp=abs((p[b.from] ?? 0)-(p[b.to] ?? 0));let open=max(0.05,b.regulatorPercent/100);branches[i].airflowCFM=250_000*sqrt(dp/max(0.1,b.resistance/open))}}
}
public struct EEMultiStageMineWater:Sendable,Codable,Equatable { public var faceSump=45.0, midSump=35.0, surfaceTank=25.0; public var facePumpGPM=650.0, boosterGPM=900.0, inflowGPM=500.0; public init(){}; public mutating func tick(dt:Double){faceSump=max(0,min(100,faceSump+(inflowGPM-facePumpGPM)*dt/5000));midSump=max(0,min(100,midSump+(facePumpGPM-boosterGPM)*dt/7000));surfaceTank=max(0,min(100,surfaceTank+boosterGPM*dt/12000))} }

public struct EECoalBlend:Sendable,Codable,Equatable { public var mine:EEMineID; public var tph:Double, ashPercent:Double, moisturePercent:Double; public init(mine:EEMineID,tph:Double,ashPercent:Double,moisturePercent:Double){self.mine=mine;self.tph=tph;self.ashPercent=ashPercent;self.moisturePercent=moisturePercent} }
public struct EECoalQuality:Sendable,Codable,Equatable { public var ashPercent:Double, moisturePercent:Double; public static func blend(_ x:[EECoalBlend])->EECoalQuality{let t=max(1,x.reduce(0){$0+$1.tph});return .init(ashPercent:x.reduce(0){$0+$1.tph*$1.ashPercent}/t,moisturePercent:x.reduce(0){$0+$1.tph*$1.moisturePercent}/t)} }
public enum EEPrepMachineKind:String,Sendable,Codable { case rawScreen, crusher, heavyMediaBath, heavyMediaCyclone, spiral, flotation, magneticSeparator, centrifuge, thickener, pump, sump }
public struct EEPrepMachine:Sendable,Codable,Equatable { public var id:String; public var kind:EEPrepMachineKind; public var ratedTPH:Double; public var feedTPH=0.0; public var health=1.0; public var motorAmps=0.0; public var outputTPH:Double { min(feedTPH,ratedTPH)*max(0,health) }; public init(id:String,kind:EEPrepMachineKind,ratedTPH:Double){self.id=id;self.kind=kind;self.ratedTPH=ratedTPH}; public mutating func tick(){motorAmps = 25 + 180*min(1,feedTPH/max(1,ratedTPH))/max(0.25,health)} }
public struct EEMagnetiteCircuit:Sendable,Codable,Equatable { public var inventoryTons=80.0, mediumSG=1.45, lossTPH=0.12, recoveryEfficiency=0.97; public init(){}; public mutating func tick(feedTPH:Double,dt:Double){inventoryTons=max(0,inventoryTons-lossTPH*(1-recoveryEfficiency)*feedTPH/1000*dt/3600);mediumSG=max(1.1,min(2.0,1.2+inventoryTons/320))} }
public struct EEFlotationBank:Sendable,Codable,Equatable { public var feedTPH=400.0, frotherRate=1.0, airRate=1.0, recovery=0.86; public var cleanTPH:Double { feedTPH*recovery*min(1.1,max(0.5,(frotherRate+airRate)/2)) } }
public struct EEThickenerDynamics:Sendable,Codable,Equatable { public var bedPercent=45.0, torquePercent=35.0, overflowClarity=0.9, underflowTPH=120.0; public init(){}; public mutating func tick(feedSolidsTPH:Double,dt:Double){bedPercent=max(0,min(100,bedPercent+(feedSolidsTPH-underflowTPH)*dt/3000));torquePercent=25+bedPercent*0.7;overflowClarity=max(0.1,1-bedPercent/180)} }

public struct EETrainCar:Sendable,Codable,Equatable { public var index:Int; public var targetTons=110.0, loadedTons=0.0; public var complete:Bool { loadedTons>=targetTons-0.5 } }
public struct EEAdvancedTrainLoadout:Sendable,Codable,Equatable { public var carIndex=0; public var positionErrorM=0.0; public var weighBinTons=0.0; public var loadCellBias=0.0; public var cars:[EETrainCar]=(0..<212).map{.init(index:$0)}; public init(){}; public mutating func batchLoad(){guard carIndex<cars.count else{return};let measured=110+loadCellBias;weighBinTons=measured;cars[carIndex].loadedTons=110;carIndex+=1} }

public enum EECoalEvidenceKind:String,Sendable,Codable { case electrical, mechanical, process, ventilation, water, quality, historian, alarm }
public struct EECoalEvidence:Sendable,Codable,Equatable { public var t:Double; public var identity:String; public var kind:EECoalEvidenceKind; public var value:String }
public struct EECoalWorkOrder:Sendable,Codable,Equatable { public var id:String, identity:String, symptom:String; public var evidence:[EECoalEvidence]=[]; public var rootCauseProven=false }

public struct EECoalDeepMine:Sendable,Codable,Equatable {
 public var id:EEMineID; public var longwall=EELongwallSystem(); public var development=EEContinuousSection(); public var power:EEMinePowerCenter; public var belts:[EEUndergroundBelt]; public var ventilation=EEVentilationNetwork(); public var water=EEMultiStageMineWater()
 public init(id:EEMineID){self.id=id;power = .init(id:"PC-\(id.rawValue)");belts=[.init(conveyor:.init(id:"UG-\(id.rawValue)-1",source:"Face",destination:"Mainline",lengthM:2500,speedMPS:3.5,ratedTPH:2500)),.init(conveyor:.init(id:"UG-\(id.rawValue)-2",source:"Mainline",destination:"Portal",lengthM:4000,speedMPS:4,ratedTPH:3000))];for i in belts.indices{belts[i].conveyor.commandedTPH=1800}}
 public mutating func tick(dt:Double){longwall.tick(dt:dt);for i in belts.indices{belts[i].tick(dt:dt)};ventilation.solve();water.tick(dt:dt)}
}

public struct EECoalMiningRev42:Sendable,Codable,Equatable {
 public var world:EEIndustrialWorld = .coalMining
 public var base=EECoalMiningComplex(); public var deepMines:[EEMineID:EECoalDeepMine]=[.northRidge:.init(id:.northRidge),.creekFork:.init(id:.creekFork),.liberty:.init(id:.liberty)]
 public var prepMachines:[EEPrepMachine]=[
  .init(id:"SCR-101",kind:.rawScreen,ratedTPH:8200),.init(id:"CR-101",kind:.crusher,ratedTPH:2500),.init(id:"HMB-101",kind:.heavyMediaBath,ratedTPH:3000),.init(id:"HMC-101",kind:.heavyMediaCyclone,ratedTPH:4200),.init(id:"SP-101",kind:.spiral,ratedTPH:1200),.init(id:"FLT-101",kind:.flotation,ratedTPH:900),.init(id:"MAG-101",kind:.magneticSeparator,ratedTPH:1000),.init(id:"CENT-101",kind:.centrifuge,ratedTPH:3000),.init(id:"THK-101",kind:.thickener,ratedTPH:1200)]
 public var magnetite=EEMagnetiteCircuit(); public var flotation=EEFlotationBank(); public var thickener=EEThickenerDynamics(); public var train=EEAdvancedTrainLoadout(); public var evidence:[EECoalEvidence]=[]; public var workOrders:[EECoalWorkOrder]=[]
 public init(){}
 public var blendedQuality:EECoalQuality { EECoalQuality.blend(base.mines.map{.init(mine:$0.id,tph:$0.deliveredTPH,ashPercent:$0.rawAshPercent,moisturePercent:$0.moisturePercent)}) }
 public mutating func tick(seconds:Double){let dt=max(0,seconds);base.tick(seconds:dt);for k in deepMines.keys{var m=deepMines[k]!;m.tick(dt:dt);deepMines[k]=m};let feed=base.totalMineTPH;for i in prepMachines.indices{prepMachines[i].feedTPH=min(prepMachines[i].ratedTPH,feed);prepMachines[i].tick()};magnetite.tick(feedTPH:feed,dt:dt);flotation.feedTPH=min(900,feed*0.12);thickener.tick(feedSolidsTPH:base.prep.reduce(0){$0+$1.refuseTPH}*0.45,dt:dt);evaluateFaults()}
 public mutating func evaluateFaults(){for (_,m) in deepMines { for b in m.belts where !b.safety.permissive { let id=b.conveyor.id;if !workOrders.contains(where:{$0.identity==id}){workOrders.append(.init(id:"WO-\(id)",identity:id,symptom:"Underground belt permissive lost"))} } }; if thickener.torquePercent>80 && !workOrders.contains(where:{$0.identity=="THK-101"}){workOrders.append(.init(id:"WO-THK-101",identity:"THK-101",symptom:"Thickener torque high"))} }
}

// MARK: - Rev43 Coal Mine & Preparation Plant Forensic Physics
// Coal-only process depth. No natural-gas process types or state are introduced here.
public struct EELongwallShield: Sendable, Codable, Equatable {
 public var index:Int; public var leftLegBar=310.0, rightLegBar=310.0, canopyM=2.2, advanceM=0.0, hydraulicLeak=0.0; public var valveHealthy=true, commHealthy=true
 public init(index:Int){self.index=index}
 public mutating func tick(dt:Double, shearerM:Double, spacingM:Double){let x=Double(index)*spacingM;let near=abs(x-shearerM)<spacingM*3;if near && valveHealthy && commHealthy {advanceM=min(1.0,advanceM+0.08*dt)};let leak=max(0,hydraulicLeak);leftLegBar=max(0,leftLegBar-leak*dt);rightLegBar=max(0,rightLegBar-leak*dt)}
}
public struct EEShearerForensics: Sendable, Codable, Equatable { public var positionM=20.0, speedMPS=0.12, headgateDrumAmps=520.0, tailgateDrumAmps=505.0, headgateHeightM=2.1, tailgateHeightM=2.0, haulageAmps=140.0, vibrationMMPS=2.2; public mutating func tick(dt:Double,hardness:Double){positionM += speedMPS*dt;headgateDrumAmps=480+180*hardness;tailgateDrumAmps=470+170*hardness;haulageAmps=120+70*hardness;vibrationMMPS=1.8+1.4*hardness} }
public struct EEAFCForensics: Sendable, Codable, Equatable { public init(){}; public var panCount=180, chainTensionKN=950.0, headDriveAmps=430.0, tailDriveAmps=410.0, brokenFlights=0, jamSeverity=0.0; public mutating func tick(load:Double){let drag=1+Double(brokenFlights)*0.015+jamSeverity;headDriveAmps=300+220*load*drag;tailDriveAmps=290+205*load*drag;chainTensionKN=850+300*load*drag} }
public struct EELongwallFaceForensics: Sendable, Codable, Equatable { public var faceLengthM=300.0, hardness=0.55; public var shearer=EEShearerForensics(); public var afc=EEAFCForensics(); public var shields:[EELongwallShield]=(0..<120).map{.init(index:$0)}; public init(){}; public mutating func tick(dt:Double){shearer.tick(dt:dt,hardness:hardness);if shearer.positionM>faceLengthM{shearer.positionM=0};afc.tick(load:min(1.5,0.45+hardness*0.5));let spacing=faceLengthM/Double(max(1,shields.count));for i in shields.indices{shields[i].tick(dt:dt,shearerM:shearer.positionM,spacingM:spacing)}} }

public struct EEAtmosphereParcel: Sendable, Codable, Equatable { public var methanePercent=0.35, coPPM=3.0, smoke=0.0, tempC=20.0 }
public struct EEAtmosphericBranch: Sendable, Codable, Equatable { public var id:String, from:String, to:String; public var resistance:Double, areaM2:Double; public var regulator=1.0, airflowM3S=0.0; public var atmosphere=EEAtmosphereParcel() }
public struct EEForensicVentilationNetwork: Sendable, Codable, Equatable {
 public var fanPressurePa=1800.0, fanSpeed=1.0
 public var branches:[EEAtmosphericBranch]=[.init(id:"INTAKE-MAIN",from:"SURFACE",to:"MAIN",resistance:0.8,areaM2:18),.init(id:"MAIN-FACE",from:"MAIN",to:"FACE",resistance:1.2,areaM2:14),.init(id:"FACE-RETURN",from:"FACE",to:"RETURN",resistance:1.5,areaM2:13),.init(id:"RETURN-FAN",from:"RETURN",to:"SURFACE",resistance:0.9,areaM2:18)]
 public init(){}
 public mutating func solve(dt:Double, methaneSource:Double=0, coSource:Double=0){for i in branches.indices{let open=max(0.03,branches[i].regulator);branches[i].airflowM3S=sqrt(max(0,fanPressurePa*fanSpeed*open/max(0.05,branches[i].resistance)))*branches[i].areaM2/12};if let f=branches.firstIndex(where:{$0.id=="FACE-RETURN"}){let q=max(1,branches[f].airflowM3S);branches[f].atmosphere.methanePercent=max(0.05,0.25+methaneSource/q);branches[f].atmosphere.coPPM=max(1,3+coSource/q)} }
}

public struct EEBeltSegmentForensics: Sendable, Codable, Equatable { public var index:Int, loadTPH:Double, idlerTempC:Double=35, alignmentMM:Double=0, drag=0.0, coSource=0.0; public mutating func tick(dt:Double){idlerTempC += drag*dt*0.25;coSource = idlerTempC>75 ? (idlerTempC-75)*0.4 : 0} }
public struct EEBeltFlightForensics: Sendable, Codable, Equatable { public var id:String; public var motorAmps=220.0, speedMPS=3.5, takeupPercent=50.0; public var segments:[EEBeltSegmentForensics]; public init(id:String,count:Int=20,loadTPH:Double=1800){self.id=id;segments=(0..<count).map{.init(index:$0,loadTPH:loadTPH)} }; public mutating func tick(dt:Double){for i in segments.indices{segments[i].tick(dt:dt)};let drag=segments.reduce(0){$0+$1.drag};motorAmps=180+drag*18+segments.reduce(0){$0+$1.loadTPH}/Double(max(1,segments.count))/15} }

public struct EECoalMaterialStream: Sendable, Codable, Equatable { public var dryTPH:Double, waterTPH:Double, ashPercent:Double, magnetiteTPH:Double; public var coarseFraction:Double, fineFraction:Double, ultraFineFraction:Double; public var totalTPH:Double {dryTPH+waterTPH}; public init(dryTPH:Double,waterTPH:Double,ashPercent:Double,magnetiteTPH:Double=0,coarseFraction:Double=0.45,fineFraction:Double=0.4,ultraFineFraction:Double=0.15){self.dryTPH=dryTPH;self.waterTPH=waterTPH;self.ashPercent=ashPercent;self.magnetiteTPH=magnetiteTPH;self.coarseFraction=coarseFraction;self.fineFraction=fineFraction;self.ultraFineFraction=ultraFineFraction} }
public struct EEPrepMassBalance: Sendable, Codable, Equatable { public var feed:EECoalMaterialStream; public var clean:EECoalMaterialStream; public var refuse:EECoalMaterialStream; public var inventoryChangeTPH:Double; public var dryErrorTPH:Double {feed.dryTPH-clean.dryTPH-refuse.dryTPH-inventoryChangeTPH}; public var waterErrorTPH:Double {feed.waterTPH-clean.waterTPH-refuse.waterTPH} }
public struct EEHeavyMediaForensics: Sendable, Codable, Equatable { public init(){}; public var correctedMediumSG=1.45, cyclonePressureKPa=85.0, magnetiteInventoryTons=80.0, magneticRecovery=0.97, dilutionWaterTPH=180.0, cycloneWear=0.0; public mutating func process(_ feed:EECoalMaterialStream)->EEPrepMassBalance{let densityEffect=max(0.65,min(0.95,0.82+(correctedMediumSG-1.4)*0.25-cycloneWear*0.08));let cleanDry=feed.dryTPH*densityEffect;let refuseDry=feed.dryTPH-cleanDry;let cleanAsh=max(2,feed.ashPercent*(1-densityEffect*0.72));let refuseAsh=min(95,feed.ashPercent+(100-feed.ashPercent)*densityEffect*0.55);let clean=EECoalMaterialStream(dryTPH:cleanDry,waterTPH:feed.waterTPH*0.48,ashPercent:cleanAsh,magnetiteTPH:feed.dryTPH*0.002*(1-magneticRecovery));let refuse=EECoalMaterialStream(dryTPH:refuseDry,waterTPH:feed.waterTPH*0.52,ashPercent:refuseAsh,magnetiteTPH:feed.dryTPH*0.002*(1-magneticRecovery));return .init(feed:feed,clean:clean,refuse:refuse,inventoryChangeTPH:0)} }
public struct EEFlotationCell: Sendable, Codable, Equatable { public var index:Int, air=1.0, frother=1.0, pulpLevel=0.6, recovery=0.82; public init(index:Int){self.index=index}; public mutating func tick(){recovery=max(0.2,min(0.96,0.68+0.08*air+0.06*frother-0.05*abs(pulpLevel-0.6)))} }
public struct EEFlotationTrain: Sendable, Codable, Equatable { public var cells:[EEFlotationCell]=(0..<6).map{.init(index:$0)}; public mutating func tick(){for i in cells.indices{cells[i].tick()}}; public var recovery:Double {cells.map{$0.recovery}.reduce(0,+)/Double(max(1,cells.count))} }
public struct EEThickenerForensics: Sendable, Codable, Equatable { public init(){}; public var bedDepthM=2.4, rakeTorquePercent=38.0, underflowSolids=0.42, overflowTurbidity=12.0, flocculant=1.0; public mutating func tick(feedSolidsTPH:Double,underflowTPH:Double,dt:Double){bedDepthM=max(0.2,min(8,bedDepthM+(feedSolidsTPH-underflowTPH)*dt/12000));rakeTorquePercent=min(150,18+bedDepthM*18);underflowSolids=max(0.2,min(0.7,0.32+bedDepthM*0.035));overflowTurbidity=max(2,30-flocculant*12+bedDepthM*1.8)} }

public struct EECoalLabSample: Sendable, Codable, Equatable { public var id:String, collectedAt:Double, resultAt:Double, ashPercent:Double, moisturePercent:Double, source:String; public var available:Bool=false }
public struct EECoalQualityLab: Sendable, Codable, Equatable { public init(){}; public var samples:[EECoalLabSample]=[]; public mutating func collect(time:Double,source:String,ash:Double,moisture:Double,delay:Double=1200){samples.append(.init(id:"LAB-\(samples.count+1)",collectedAt:time,resultAt:time+delay,ashPercent:ash,moisturePercent:moisture,source:source))}; public mutating func tick(time:Double){for i in samples.indices where time>=samples[i].resultAt {samples[i].available=true}} }
public enum EELoadoutPhase:String,Sendable,Codable { case approach, position, fillBin, settle, verify, dump, advance, complete }
public struct EEForensicTrainLoadout: Sendable, Codable, Equatable { public init(){}; public var phase:EELoadoutPhase = .approach, car=0, binTons=0.0, carTons=0.0, positionErrorM=0.0, scaleBiasTons=0.0; public var targetTons=110.0; public mutating func step(){switch phase{case .approach:phase = .position;case .position:if abs(positionErrorM)<0.25{phase = .fillBin};case .fillBin:binTons=targetTons+scaleBiasTons;phase = .settle;case .settle:phase = .verify;case .verify:phase = .dump;case .dump:carTons=binTons;binTons=0;phase = .advance;case .advance:car += 1;carTons=0;phase = car>=212 ? .complete:.approach;case .complete:break}} }

public struct EECoalMiningRev43: Sendable, Codable, Equatable {
 public var world:EEIndustrialWorld = .coalMining; public var rev42=EECoalMiningRev42(); public var time=0.0
 public var longwalls:[EEMineID:EELongwallFaceForensics]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var ventilation:[EEMineID:EEForensicVentilationNetwork]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var belts:[EEMineID:EEBeltFlightForensics]=[.northRidge:.init(id:"NR-MAIN"),.creekFork:.init(id:"CF-MAIN"),.liberty:.init(id:"LB-MAIN")]
 public var heavyMedia=EEHeavyMediaForensics(); public var flotation=EEFlotationTrain(); public var thickener=EEThickenerForensics(); public var lab=EECoalQualityLab(); public var loadout=EEForensicTrainLoadout()
 public init(){}
 public mutating func tick(seconds:Double){let dt=max(0,seconds);time += dt;rev42.tick(seconds:dt);for k in longwalls.keys{var x=longwalls[k]!;x.tick(dt:dt);longwalls[k]=x};for k in belts.keys{var b=belts[k]!;b.tick(dt:dt);belts[k]=b};for k in ventilation.keys{var v=ventilation[k]!;let co=belts[k]?.segments.reduce(0){$0+$1.coSource} ?? 0;v.solve(dt:dt,methaneSource:4,coSource:co);ventilation[k]=v};flotation.tick();thickener.tick(feedSolidsTPH:180,underflowTPH:165,dt:dt);lab.tick(time:time)}
 public func massBalance(feed:EECoalMaterialStream)->EEPrepMassBalance {var h=heavyMedia; return h.process(feed)}
}

// MARK: - Rev44 Coal Systems Forensic Depth
// Coal/mining only. Natural-gas process state remains isolated in its own world.
public struct EEHydraulicManifold: Sendable, Codable, Equatable { public init(){};
 public var supplyBar=330.0, returnBar=18.0, accumulatorBar=300.0, contamination=0.0, pumpHealth=1.0
 public var solenoids:[Bool]=Array(repeating:false,count:8)
 public mutating func tick(dt:Double,demand:Double){let d=max(0,min(1,demand));supplyBar=max(120,min(350,supplyBar+(330*max(0.2,pumpHealth)-supplyBar)*0.08*dt-d*3*dt));accumulatorBar=max(returnBar,accumulatorBar-d*0.7*dt+(supplyBar-accumulatorBar)*0.02*dt);contamination=min(1,contamination+max(0,1-pumpHealth)*dt/5000)}
}
public struct EEShearerDrumHealth: Sendable, Codable, Equatable { public init(){}; public var bitWear=0.05, missingBits=0, bearingHealth=1.0, gearboxHealth=1.0; public var torqueMultiplier:Double {1 + bitWear*0.55 + Double(missingBits)*0.035 + (1-bearingHealth)*0.5 + (1-gearboxHealth)*0.65} }
public struct EEAFCChainDynamics: Sendable, Codable, Equatable { public init(){}; public var pretensionKN=620.0, elongationPercent=0.1, sprocketWear=0.05, gearboxHealth=1.0, chainSpeedMPS=1.4; public var dynamicTensionKN:Double=620; public mutating func tick(load:Double,dt:Double){dynamicTensionKN=pretensionKN*(1+0.55*max(0,load)+elongationPercent*0.03+sprocketWear*0.25);elongationPercent=min(8,elongationPercent+max(0,load-0.8)*dt/5000);gearboxHealth=max(0.1,gearboxHealth-max(0,load-0.9)*dt/20000)} }
public struct EEDevelopmentMachineForensics: Sendable, Codable, Equatable { public init(){}; public var cutterWear=0.08, hydraulicPressureBar=180.0, bolterPressureBar=160.0, haulageBatterySOC=0.9, feederCrusherWear=0.05; public var cutterAmps:Double {360*(1+cutterWear*0.8)}; public mutating func tick(dt:Double){haulageBatterySOC=max(0,haulageBatterySOC-dt/40000);hydraulicPressureBar=max(80,180-cutterWear*30);bolterPressureBar=max(80,160-feederCrusherWear*20)} }

public struct EEFanCurvePoint: Sendable, Codable, Equatable { public var flowM3S:Double, pressurePa:Double }
public struct EENonlinearMineFan: Sendable, Codable, Equatable { public init(){}; public var speed=1.0, efficiency=0.82, points:[EEFanCurvePoint]=[.init(flowM3S:0,pressurePa:2600),.init(flowM3S:100,pressurePa:2300),.init(flowM3S:200,pressurePa:1600),.init(flowM3S:280,pressurePa:700)]; public func pressure(at flow:Double)->Double {let f=max(0,flow);let scaled=f/max(0.1,speed);for i in 1..<points.count where scaled<=points[i].flowM3S {let a=points[i-1],b=points[i];let r=(scaled-a.flowM3S)/max(0.001,b.flowM3S-a.flowM3S);return max(0,(a.pressurePa+(b.pressurePa-a.pressurePa)*r)*speed*speed)};return max(0,points.last!.pressurePa*speed*speed)} }
public struct EEAtmosphericSensor: Sendable, Codable, Equatable { public var id:String, distanceM:Double, methanePercent=0.0, coPPM=0.0, temperatureC=22.0, responseSeconds=8.0; public mutating func sample(sourceMethane:Double,sourceCO:Double,airVelocity:Double,dt:Double){let delay=max(0,distanceM/max(0.1,airVelocity));let alpha=max(0,min(1,dt/max(0.1,responseSeconds+delay*0.02)));methanePercent += (sourceMethane-methanePercent)*alpha;coPPM += (sourceCO-coPPM)*alpha} }
public struct EEMineAtmosphericNetwork: Sendable, Codable, Equatable { public init(){}; public var sensors:[EEAtmosphericSensor]=[.init(id:"HG-ATM-1",distanceM:50),.init(id:"TG-ATM-1",distanceM:180),.init(id:"RET-ATM-1",distanceM:600)]; public mutating func tick(methane:Double,co:Double,airVelocity:Double,dt:Double){for i in sensors.indices{sensors[i].sample(sourceMethane:methane,sourceCO:co,airVelocity:airVelocity,dt:dt)}} }

public struct EEPumpCurvePoint: Sendable, Codable, Equatable { public var gpm:Double, headM:Double }
public struct EEMinePumpHydraulics: Sendable, Codable, Equatable { public init(){}; public var speed=1.0, impellerHealth=1.0, suctionHeadM=4.0, staticHeadM=90.0, valveOpen=1.0, pipeResistance=0.00008; public var curve:[EEPumpCurvePoint]=[.init(gpm:0,headM:150),.init(gpm:500,headM:125),.init(gpm:1000,headM:80),.init(gpm:1400,headM:30)]; public var flowGPM:Double {let available=max(0,curve[0].headM*speed*speed*impellerHealth-staticHeadM);return min(1400,max(0,sqrt(available/max(0.000001,pipeResistance))*valveOpen))}; public var cavitationRisk:Double {max(0,min(1,(3-suctionHeadM)/3))} }
public struct EEBeltTakeUp: Sendable, Codable, Equatable { public init(){}; public var targetTensionKN=180.0, actualTensionKN=180.0, carriageM=4.0, travelLimitM=8.0, hydraulicPressureBar=120.0; public mutating func tick(load:Double,dt:Double){let desired=targetTensionKN*(1+0.35*max(0,load));actualTensionKN += (desired-actualTensionKN)*min(1,dt/4);carriageM=min(travelLimitM,max(0,4+(actualTensionKN-targetTensionKN)/80))} }

public struct EEMediumLoopForensics: Sendable, Codable, Equatable { public init(){}; public var correctedSG=1.45, diluteSG=1.18, correctedSumpPercent=60.0, diluteSumpPercent=55.0, magneticSeparatorRecovery=0.97, rinseWaterTPH=160.0, densityBias=0.0; public mutating func tick(feedTPH:Double,dt:Double){let loss=feedTPH*(1-magneticSeparatorRecovery)*0.00002*dt;correctedSG=max(1.15,min(1.8,correctedSG-loss-rinseWaterTPH*dt/20_000_000));diluteSG=max(1.05,min(correctedSG,diluteSG+(correctedSG-diluteSG)*0.01*dt));correctedSumpPercent=max(5,min(95,correctedSumpPercent-loss*2));diluteSumpPercent=max(5,min(95,diluteSumpPercent+loss))}; public var indicatedCorrectedSG:Double {correctedSG+densityBias} }
public struct EEDrainRinseScreen: Sendable, Codable, Equatable { public init(){}; public var apertureMM=0.8, blindedFraction=0.05, vibrationMM=5.0, rinseWaterTPH=80.0; public var recoveryEfficiency:Double {max(0.5,min(0.995,0.985-blindedFraction*0.35+min(0.02,vibrationMM/500)))} }
public struct EECentrifugeForensics: Sendable, Codable, Equatable { public init(){}; public var rpm=900.0, vibrationMMPS=2.0, bearingTempC=48.0, basketWear=0.05, feedTPH=800.0; public var productMoisturePercent:Double {max(4,min(18,8+basketWear*6+max(0,900-rpm)/180))}; public mutating func tick(dt:Double){vibrationMMPS=max(1,2+basketWear*9);bearingTempC += max(0,vibrationMMPS-5)*dt/300} }
public struct EEDustCollectorForensics: Sendable, Codable, Equatable { public init(){}; public var differentialPressureInWG=3.0, fanAmps=45.0, hopperPercent=25.0, filterLoading=0.15; public mutating func tick(dustLoad:Double,dt:Double){filterLoading=min(1,filterLoading+dustLoad*dt/20000);differentialPressureInWG=2+filterLoading*8;fanAmps=40+differentialPressureInWG*2;hopperPercent=min(100,hopperPercent+dustLoad*dt/1000)} }
public struct EESiloFlowForensics: Sendable, Codable, Equatable { public init(){}; public var tons=8000.0, capacityTons=17000.0, ratholeFraction=0.0, bridgeStrength=0.0, feederCommandTPH=1000.0; public var effectiveOutflowTPH:Double {feederCommandTPH*max(0,1-ratholeFraction)*max(0,1-bridgeStrength)}; public mutating func tick(inflowTPH:Double,dt:Double){tons=max(0,min(capacityTons,tons+(inflowTPH-effectiveOutflowTPH)*dt/3600))} }
public struct EECoalSamplerForensics: Sendable, Codable, Equatable { public init(){}; public var cutterHealth=1.0, intervalSeconds=300.0, biasAshPoints=0.0, lastSampleTime = -1.0; public mutating func shouldSample(time:Double)->Bool {if lastSampleTime < 0 || time-lastSampleTime>=intervalSeconds {lastSampleTime=time;return true};return false} }
public struct EEInstrumentedRailCar: Sendable, Codable, Equatable { public var index:Int, targetTons:Double=110, actualTons:Double=0, indicatedTons:Double=0, positionM:Double=0, loaded=false }
public struct EEInstrumentedTrainLoadout: Sendable, Codable, Equatable { public init(){}; public var cars:[EEInstrumentedRailCar]=(0..<212).map{.init(index:$0)}; public var activeCar=0, weighBinTons=0.0, scaleBias=0.0, gateTravel=0.0, feederTPH=1800.0; public mutating func tick(dt:Double){guard activeCar<cars.count else{return};gateTravel=min(1,gateTravel+dt/2);weighBinTons=min(110+scaleBias,weighBinTons+feederTPH*dt/3600);if weighBinTons>=109.5+scaleBias {cars[activeCar].actualTons=weighBinTons-scaleBias;cars[activeCar].indicatedTons=weighBinTons;cars[activeCar].loaded=true;weighBinTons=0;gateTravel=0;activeCar+=1}} }

public struct EECoalIncidentFrame: Sendable, Codable, Equatable { public init(time:Double,mine:EEMineID,beltAmps:Double,maxIdlerC:Double,methanePercent:Double,coPPM:Double,longwallAFCAmps:Double,prepSG:Double,thickenerTorque:Double,loadedCars:Int){self.time=time;self.mine=mine;self.beltAmps=beltAmps;self.maxIdlerC=maxIdlerC;self.methanePercent=methanePercent;self.coPPM=coPPM;self.longwallAFCAmps=longwallAFCAmps;self.prepSG=prepSG;self.thickenerTorque=thickenerTorque;self.loadedCars=loadedCars}; public var time:Double, mine:EEMineID, beltAmps:Double, maxIdlerC:Double, methanePercent:Double, coPPM:Double, longwallAFCAmps:Double, prepSG:Double, thickenerTorque:Double, loadedCars:Int }
public struct EECoalIncidentRecorder: Sendable, Codable, Equatable { public init(){}; public var frames:[EECoalIncidentFrame]=[]; public mutating func append(_ f:EECoalIncidentFrame){frames.append(f);if frames.count>7200{frames.removeFirst(frames.count-7200)}}; public func nearest(time:Double)->EECoalIncidentFrame? {frames.min{abs($0.time-time)<abs($1.time-time)}} }

public struct EECoalMiningRev44: Sendable, Codable, Equatable {
 public var world:EEIndustrialWorld = .coalMining; public var rev43=EECoalMiningRev43(); public var time=0.0
 public var hydraulics:[EEMineID:EEHydraulicManifold]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var drums:[EEMineID:EEShearerDrumHealth]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var chains:[EEMineID:EEAFCChainDynamics]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var development:[EEMineID:EEDevelopmentMachineForensics]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var atmosphere:[EEMineID:EEMineAtmosphericNetwork]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var pumps:[EEMineID:EEMinePumpHydraulics]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var takeups:[EEMineID:EEBeltTakeUp]=[.northRidge:.init(),.creekFork:.init(),.liberty:.init()]
 public var medium=EEMediumLoopForensics(), drainRinse=EEDrainRinseScreen(), centrifuge=EECentrifugeForensics(), dust=EEDustCollectorForensics(), silo=EESiloFlowForensics(), sampler=EECoalSamplerForensics(), train=EEInstrumentedTrainLoadout(), recorder=EECoalIncidentRecorder()
 public init(){}
 public mutating func tick(seconds:Double){let dt=max(0,seconds);time+=dt;rev43.tick(seconds:dt);for mine in [EEMineID.northRidge,.creekFork,.liberty]{var h=hydraulics[mine]!;h.tick(dt:dt,demand:rev43.longwalls[mine]!.afc.headDriveAmps/1000);hydraulics[mine]=h;var c=chains[mine]!;c.tick(load:rev43.longwalls[mine]!.afc.headDriveAmps/900,dt:dt);chains[mine]=c;var d=development[mine]!;d.tick(dt:dt);development[mine]=d;var a=atmosphere[mine]!;let vent=rev43.ventilation[mine]!;let q=max(1,vent.branches.reduce(0){$0+$1.airflowM3S}/Double(max(1,vent.branches.count)));let co=rev43.belts[mine]!.segments.reduce(0){$0+$1.coSource};a.tick(methane:vent.branches.last?.atmosphere.methanePercent ?? 0,co:co,airVelocity:q/25,dt:dt);atmosphere[mine]=a;var t=takeups[mine]!;t.tick(load:rev43.belts[mine]!.motorAmps/300,dt:dt);takeups[mine]=t};medium.tick(feedTPH:rev43.rev42.base.totalMineTPH,dt:dt);centrifuge.tick(dt:dt);dust.tick(dustLoad:rev43.rev42.base.totalMineTPH/1000,dt:dt);silo.tick(inflowTPH:rev43.rev42.base.totalMineTPH,dt:dt);if sampler.shouldSample(time:time){let q=rev43.rev42.blendedQuality;rev43.lab.collect(time:time,source:"CPP-FEED",ash:q.ashPercent+sampler.biasAshPoints,moisture:q.moisturePercent,delay:1200)};train.tick(dt:dt);let mine:EEMineID = .northRidge;let belt=rev43.belts[mine]!;let atm=atmosphere[mine]!.sensors.last!;recorder.append(.init(time:time,mine:mine,beltAmps:belt.motorAmps,maxIdlerC:belt.segments.map{$0.idlerTempC}.max() ?? 0,methanePercent:atm.methanePercent,coPPM:atm.coPPM,longwallAFCAmps:rev43.longwalls[mine]!.afc.headDriveAmps,prepSG:medium.indicatedCorrectedSG,thickenerTorque:rev43.thickener.rakeTorquePercent,loadedCars:train.activeCar))}
}
