import Foundation

// MARK: - Rev56 Reference Validation + Mastery Training
public enum EEIntegrationMethod56:String,CaseIterable,Sendable,Codable {case backwardEuler,trapezoidal}
public struct EEReferencePoint56:Sendable,Codable,Equatable {public var t:Double;public var expected:Double;public var actual:Double;public var error:Double{actual-expected}}
public struct EEReferenceRun56:Identifiable,Sendable,Codable,Equatable {public var id:String;public var category:String;public var points: [EEReferencePoint56];public var tolerance:Double;public var maxError:Double{points.map{abs($0.error)}.max() ?? 0};public var rmsError:Double{guard !points.isEmpty else{return 0};return sqrt(points.map{$0.error*$0.error}.reduce(0,+)/Double(points.count))};public var passed:Bool{maxError<=tolerance}}
public struct EEReferenceHarness56:Sendable,Codable,Equatable {
 public var runs: [EEReferenceRun56] = [];public init(){}
 public mutating func runRC(method:EEIntegrationMethod56,source:Double=10,r:Double=1000,c:Double=1e-6,dt:Double=1e-5,duration:Double=0.005){let tau=r*c;var t=0.0,v=0.0;var pts: [EEReferencePoint56] = [];while t<duration-0.5*dt{let old=v;switch method{case .backwardEuler:v=(old+dt*source/tau)/(1+dt/tau);case .trapezoidal:let a=dt/(2*tau);v=((1-a)*old+2*a*source)/(1+a)};t += dt;let expected=source*(1-exp(-t/tau));pts.append(.init(t:t,expected:expected,actual:v))};runs.append(.init(id:"RC-\(method.rawValue)",category:"transient",points:pts,tolerance:method == .trapezoidal ? 0.0002:0.02))}
 public mutating func runRL(method:EEIntegrationMethod56,source:Double=10,r:Double=10,l:Double=0.1,dt:Double=1e-5,duration:Double=0.05){let tau=l/r;var t=0.0,i=0.0;var pts: [EEReferencePoint56] = [];while t<duration-0.5*dt{let old=i;switch method{case .backwardEuler:i=(old+dt*source/l)/(1+dt*r/l);case .trapezoidal:let a=dt*r/(2*l);i=((1-a)*old+dt*source/l)/(1+a)};t += dt;let expected=(source/r)*(1-exp(-t/tau));pts.append(.init(t:t,expected:expected,actual:i))};runs.append(.init(id:"RL-\(method.rawValue)",category:"transient",points:pts,tolerance:method == .trapezoidal ? 0.00002:0.002))}
 public mutating func runAll(){runs=[];for m in EEIntegrationMethod56.allCases{runRC(method:m);runRL(method:m)}};public var passed:Bool{!runs.isEmpty && runs.allSatisfy{$0.passed}}
}
public struct EEConservationAudit56:Sendable,Codable,Equatable {public var kclResidual:Double;public var kvlResidual:Double;public var powerResidual:Double;public var passed:Bool{abs(kclResidual)<1e-9 && abs(kvlResidual)<1e-9 && abs(powerResidual)<1e-9};public static func divider(source:Double=10,r1:Double=1000,r2:Double=1000)->Self{let i=source/(r1+r2),v2=i*r2;return .init(kclResidual:i-i,kvlResidual:source-i*r1-v2,powerResidual:source*i-i*i*r1-i*i*r2)}}

public enum EETrainingSchool56:String,CaseIterable,Sendable,Codable {case fundamentals,electronics,motorControls,industrialPower,instrumentation,plcAutomation,drives,networks,processControls,advancedDiagnostics,naturalGasIE,coalMiningIE,embeddedSystems,engineeringAnalysis,safetyCommissioning,forensicEngineering}
public enum EETrainingStage56:String,CaseIterable,Sendable,Codable {case observe,explain,guidedBuild,independentBuild,measure,commission,faultedDiagnose,repair,prove,teachBack,masteryChallenge}
public enum EECompetency56:String,CaseIterable,Sendable,Codable {case theory,schematicReading,physicalConstruction,instrumentUse,measurementPlanning,safetyIsolation,commissioning,diagnosis,rootCause,repairVerification,documentation,automation,processReasoning,numericalReasoning}
public enum EELessonMode56:String,CaseIterable,Sendable,Codable {case demonstration,guided,assisted,independent,assessment,forensicCase,sandbox}
public struct EETrainingObjective56:Identifiable,Sendable,Codable,Equatable {public var id:String;public var text:String;public var competency:EECompetency56;public var requiredEvidence:Int;public init(_ id:String,_ text:String,_ competency:EECompetency56,_ requiredEvidence:Int=1){self.id=id;self.text=text;self.competency=competency;self.requiredEvidence=requiredEvidence}}
public struct EETrainingLesson56:Identifiable,Sendable,Codable,Equatable {public var id:String;public var title:String;public var school:EETrainingSchool56;public var stage:EETrainingStage56;public var mode:EELessonMode56;public var objectives: [EETrainingObjective56];public var prerequisiteIDs: [String];public var allowedInstruments: [String];public var faultFamilies: [String];public var estimatedMinutes:Int;public var xp:Int}
public struct EEAssessmentRecord56:Sendable,Codable,Equatable {public var lessonID:String;public var evidenceCount:Int;public var unsafeActions:Int;public var hints:Int;public var rootCauseCorrect:Bool;public var repairVerified:Bool;public var score:Double}
public struct EEMastery56:Sendable,Codable,Equatable {public var competency:EECompetency56;public var attempts:Int=0;public var mastery:Double=0;public mutating func update(score:Double){attempts += 1;let alpha=attempts<3 ? 0.55:0.3;mastery=min(1,max(0,mastery*(1-alpha)+score*alpha))}}
public struct EETrainingCatalog56:Sendable,Codable,Equatable {
 public var lessons: [EETrainingLesson56] = [];public init(){build()}
 mutating func build(){lessons=[];let topics: [(EETrainingSchool56,[String])]=[
  (.fundamentals,["DC source and lamp","Ohm's law under load","Series and parallel","Voltage drop","RC transient"]),(.electronics,["Diode behavior","BJT bias","MOSFET switching","Op-amp signal conditioning","RLC response"]),(.motorControls,["Three-wire starter","Seal-in circuit","Jog and HOA","Reversing interlock","Contactor diagnostics"]),(.industrialPower,["Single/three phase","Transformer","MCC bucket","Protection coordination","Motor starting"]),(.instrumentation,["4–20 mA loop","Loop compliance","DP transmitter","HART configuration","Calibration as-found/as-left"]),(.plcAutomation,["Discrete I/O","Timers/counters","Analog scaling","Interlocks/permissives","PID loop"]),(.drives,["VFD power path","DC bus","PWM output","Motor/VFD coupling","Drive fault diagnosis"]),(.networks,["Ethernet physical layer","Remote I/O","Serial links","CAN termination","Noise and shielding"]),(.processControls,["Pressure loop","Flow loop","Valve response","Cause/effect","Process upset"]),(.advancedDiagnostics,["Competing hypotheses","Information gain","Intermittent fault","Thermal/vibration evidence","Forensic reconstruction"]),(.naturalGasIE,["Compressor station power","Recycle/anti-surge","Instrument air","Burner management","Gas station forensic case"]),(.coalMiningIE,["Mine power center","Belt protection","Ventilation instrumentation","Prep plant controls","Coal forensic case"]),(.embeddedSystems,["GPIO loading","PWM drive","ADC acquisition","UART/SPI/I2C","Physical CAN"]),(.engineeringAnalysis,["DC operating point","Transient integration","AC response","Monte Carlo","Conservation audit"]),(.safetyCommissioning,["Energy-source graph","Test-before-touch simulation","Commissioning sequence","Functional proof","Safe restoration"]),(.forensicEngineering,["SOE first-out","Historian correlation","PLC state reconstruction","Evidence chain","Root-cause dossier"])]
  for (school,names) in topics {for (i,name) in names.enumerated(){let id="\(school.rawValue)-\(i+1)";let comps: [EECompetency56]=[.theory,.schematicReading,.physicalConstruction,.instrumentUse,.diagnosis,.repairVerification,.numericalReasoning];let c=comps[i % comps.count];lessons.append(.init(id:id,title:name,school:school,stage:i<1 ? .observe:(i<3 ? .guidedBuild:.faultedDiagnose),mode:i<1 ? .demonstration:(i<3 ? .guided:.forensicCase),objectives: [.init("\(id)-O1","Explain the governing physical relationship",.theory),.init("\(id)-O2","Produce simulation-backed evidence",c,2),.init("\(id)-O3","Verify the result without changing physical truth",.repairVerification)],prerequisiteIDs:i==0 ? []: ["\(school.rawValue)-\(i)"],allowedInstruments: ["DMM","Oscilloscope","Clamp Meter","Process Calibrator"],faultFamilies:i>=3 ? ["open","highResistance","intermittent","misconfiguration"]: [],estimatedMinutes:15+i*10,xp:100+i*50))}}
 }
 public func unlocked(completed:Set<String>)->[EETrainingLesson56]{lessons.filter{$0.prerequisiteIDs.allSatisfy(completed.contains)}}
}
public struct EETrainingEngine56:Sendable,Codable,Equatable {public var catalog=EETrainingCatalog56();public var completed: Set<String> = [];public var records: [EEAssessmentRecord56] = [];public var mastery: [EECompetency56:EEMastery56] = [:];public init(){for c in EECompetency56.allCases{mastery[c] = .init(competency:c)}};public mutating func assess(lessonID:String,evidence:Int,unsafe:Int,hints:Int,rootCause:Bool,verified:Bool)->EEAssessmentRecord56{guard let l=catalog.lessons.first(where:{$0.id==lessonID}) else{return .init(lessonID:lessonID,evidenceCount:evidence,unsafeActions:unsafe,hints:hints,rootCauseCorrect:false,repairVerified:false,score:0)};let required=l.objectives.map{$0.requiredEvidence}.reduce(0,+);let ev=min(1,Double(evidence)/Double(max(required,1)));var s=0.25*ev+0.25*(rootCause ? 1:0)+0.25*(verified ? 1:0)+0.25*max(0,1-Double(hints)*0.15);if unsafe>0{s=min(s,0.49)};let r=EEAssessmentRecord56(lessonID:lessonID,evidenceCount:evidence,unsafeActions:unsafe,hints:hints,rootCauseCorrect:rootCause,repairVerified:verified,score:s);records.append(r);for o in l.objectives{mastery[o.competency]?.update(score:s)};if s>=0.75 && unsafe==0{completed.insert(lessonID)};return r}}
public struct EERev56NumericalTrainingExpansion:Sendable,Codable {public var base=EERev55NumericalCredibility();public var references=EEReferenceHarness56();public var training=EETrainingEngine56();public init(){}}
