import Foundation
import ElectricalCore
import CircuitMNA

// MARK: - Rev51 Technical Ceiling
// Freeform CircuitMNA bench + registry-complete Golden Thread audit + synchronized forensic replay.

public enum EEBenchSolveState51:String,Sendable,Codable { case deenergized, solved, singular, invalidTopology }
public struct EEBenchNodeVoltage51:Identifiable,Sendable,Codable,Equatable { public var id:String; public var volts:Double }
public struct EEBenchSolveResult51:Sendable,Codable,Equatable {
 public var state:EEBenchSolveState51; public var nodeVoltages:[EEBenchNodeVoltage51]; public var sourceCurrentsA:[Double]; public var residual:Double; public var islands:[[String]]; public var message:String
 public func voltage(_ terminal:String)->Double?{nodeVoltages.first{$0.id==terminal}?.volts}
}
public struct EECircuitMNABench51:Sendable,Codable,Equatable {
 public var workspace=EEBenchWorkspace48(); public var protection=EEBenchProtection49(); public var time=0.0; public var last:EEBenchSolveResult51?; public var componentDamage:[String:Double]=[:]
 public init(){}
 public mutating func add(id:String,kind:EEBenchComponentKind48,terminals:[String],value:Double,enabled:Bool=true)->Bool{guard !id.isEmpty,terminals.count>=2,!workspace.components.contains(where:{$0.id==id}),terminals.allSatisfy({!workspace.terminalExists($0)}) else{return false};workspace.components.append(.init(id:id,kind:kind,terminals:terminals,value:value,enabled:enabled));return true}
 public mutating func removeComponent(_ id:String){let ts=Set(workspace.components.first(where:{$0.id==id})?.terminals ?? []);workspace.components.removeAll{$0.id==id};workspace.wires.removeAll{ts.contains($0.from)||ts.contains($0.to)}}
 public mutating func setEnabled(_ id:String,_ enabled:Bool){if let i=workspace.components.firstIndex(where:{$0.id==id}){workspace.components[i].enabled=enabled}}
 public mutating func wire(_ a:String,_ b:String,resistanceOhm:Double=0.02)->Bool{guard workspace.terminalExists(a),workspace.terminalExists(b),a != b,resistanceOhm>0 else{return false};workspace.wire(a,b,resistanceOhm:resistanceOhm);return true}
 private func compiled()->(Circuit,[String:Int],[String])?{
  let all=workspace.components.flatMap{$0.terminals}; guard Set(all).count==all.count else{return nil}; let wired=Set(workspace.wires.filter{$0.healthy}.flatMap{[$0.from,$0.to]}); let supplyTerms=Set(workspace.components.filter{$0.kind == .supply && $0.enabled}.flatMap{$0.terminals}); let included=workspace.components.filter{c in c.kind == .supply || c.terminals.contains(where:{wired.contains($0)})}.flatMap{$0.terminals}; let terminals=Array(Set(included).union(supplyTerms)).sorted()
  let ground = workspace.components.first(where:{$0.kind == .supply})?.terminals.dropFirst().first ?? terminals.first
  guard let g=ground else{return nil}; var map:[String:Int]=[g:0];var next=1;for t in terminals where map[t]==nil{map[t]=next;next += 1}
  var rs:[Resistor]=[];var vs:[VoltageSource]=[]
  for w in workspace.wires where w.healthy {guard let a=map[w.from],let b=map[w.to] else{continue};rs.append(.init(a:a,b:b,resistance:max(1e-6,w.resistanceOhm)))}
  for c in workspace.components where c.enabled && c.terminals.count>=2 {guard let a=map[c.terminals[0]],let b=map[c.terminals[1]] else{continue};switch c.kind {
   case .supply: vs.append(.init(positive:a,negative:b,volts:c.value))
   case .resistor: rs.append(.init(a:a,b:b,resistance:max(1e-6,c.value)))
   case .lamp: let r = c.value > 0 ? max(0.01,24*24/c.value) : 1e9;rs.append(.init(a:a,b:b,resistance:r))
   case .relayCoil: rs.append(.init(a:a,b:b,resistance:max(1,c.value)))
   case .motor: rs.append(.init(a:a,b:b,resistance:max(0.05,c.value)))
   case .transmitter,.analogInput: rs.append(.init(a:a,b:b,resistance:max(50,c.value)))
   case .canTermination: rs.append(.init(a:a,b:b,resistance:max(1,c.value)))
   case .switchDevice,.relayContact: rs.append(.init(a:a,b:b,resistance:0.001))
   case .capacitor,.diode,.plcOutput,.vfd,.networkNode: break
  }}
  return(.init(nodeCount:next,resistors:rs,voltageSources:vs),map,terminals)
 }
 public mutating func solve(seconds:Double=0.01)->EEBenchSolveResult51 {time += max(0,seconds);guard workspace.energized else{let r=EEBenchSolveResult51(state:.deenergized,nodeVoltages:[],sourceCurrentsA:[],residual:0,islands:[],message:"Bench is de-energized");last=r;return r};guard let (c,map,terminals)=compiled() else{let r=EEBenchSolveResult51(state:.invalidTopology,nodeVoltages:[],sourceCurrentsA:[],residual:0,islands:[],message:"Duplicate or invalid terminal topology");last=r;return r};do{let snap=try ReferenceDCSolver().solve(c);let volts=terminals.compactMap{t -> EEBenchNodeVoltage51? in guard let n=map[t],n<snap.nodeVoltages.count else{return nil};return .init(id:t,volts:snap.nodeVoltages[n])};let inv=Dictionary(uniqueKeysWithValues:map.map{($0.value,$0.key)});let islands=IslandDetector.detect(c).map{$0.nodes.compactMap{inv[$0]}};let maxI=snap.voltageSourceCurrents.map{abs($0)}.max() ?? 0;protection.apply(currentA:maxI,seconds:seconds);if maxI>10{componentDamage["SUPPLY",default:0]=min(1,componentDamage["SUPPLY",default:0]+seconds*0.05)};if protection.state != .healthy{workspace.energized=false};let r=EEBenchSolveResult51(state:.solved,nodeVoltages:volts,sourceCurrentsA:snap.voltageSourceCurrents,residual:snap.residual,islands:islands,message:"CircuitMNA converged");last=r;return r}catch{let r=EEBenchSolveResult51(state:.singular,nodeVoltages:[],sourceCurrentsA:[],residual:1e300,islands:[],message:"Floating/open topology: \(error)");last=r;return r}}
 public mutating func energize(_ on:Bool=true){workspace.energized=on}
 public mutating func measure(red:String,black:String)->Double?{guard let r=last?.voltage(red),let b=last?.voltage(black) else{return nil};return r-b}
}

public struct EEGoldenThreadAudit51:Sendable,Codable,Equatable { public var total:Int; public var withPhysical:Int; public var withEngineering:Int; public var withHistorian:Int; public var orphanIDs:[String]; public var duplicateKeys:[String]; public var coverage:Double }
public struct EERegistryCompleteGoldenThread51:Sendable,Codable,Equatable {
 public var identities:[EEUniversalIdentity]
 public init(base:EERegistryGoldenThread49,timeline:EEForensicTimelineRev46){var map:[String:EEUniversalIdentity]=[:];func key(_ i:EEUniversalIdentity)->String{"\(i.world?.rawValue ?? "common")|\(i.id)"};for i in base.identities{map[key(i)]=i}
  for world in [EEIndustrialWorld.naturalGas,.coalMining] {for s in timeline.snapshots(for:world){for c in s.channels{let k="\(world.rawValue)|\(c.sourceIdentity)";var i=map[k] ?? .init(id:c.sourceIdentity,world:world,bindings:[]);if !i.bindings.contains(where:{$0.surface == .historian && $0.reference==c.id}){i.bindings.append(.init(.historian,c.id))};map[k]=i}}}
  identities=map.values.map{item in var i=item;if !i.bindings.contains(where:{$0.surface == .physical}){i.bindings.append(.init(.physical,"UNMAPPED:\(i.id)"))};return i}.sorted{($0.world?.rawValue ?? "")+"|"+$0.id < ($1.world?.rawValue ?? "")+"|"+$1.id}
 }
 public func identity(_ id:String,world:EEIndustrialWorld)->EEUniversalIdentity?{identities.first{$0.id==id && $0.world==world}}
 public func related(_ q:String)->[EEUniversalIdentity]{identities.filter{q.isEmpty || $0.id.localizedCaseInsensitiveContains(q)||$0.bindings.contains{$0.reference.localizedCaseInsensitiveContains(q)}}}
 public var audit:EEGoldenThreadAudit51 {var seen:Set<String>=[];var dup:[String]=[];var physical=0,engineering=0,hist=0;var orphan:[String]=[];for i in identities{let k="\(i.world?.rawValue ?? "common")|\(i.id)";if !seen.insert(k).inserted{dup.append(k)};let p=i.bindings.contains{$0.surface == .physical && !$0.reference.hasPrefix("UNMAPPED:")};let e=i.bindings.contains{[EEEngineeringSurface.oneLine,.elementary,.loopSheet,.pAndID,.plc,.hmi,.network].contains($0.surface)};let h=i.bindings.contains{$0.surface == .historian};if p{physical+=1};if e{engineering+=1};if h{hist+=1};if !p && !e && !h{orphan.append(i.id)}};let total=max(1,identities.count);return .init(total:identities.count,withPhysical:physical,withEngineering:engineering,withHistorian:hist,orphanIDs:orphan,duplicateKeys:dup,coverage:Double(identities.count-orphan.count)/Double(total))}
}

public struct EEPLCReplay51:Sendable,Codable,Equatable { public var scan:Int; public var tags:[String:Double]; public var states:[String:String] }
public struct EESOEReplayEvent51:Identifiable,Sendable,Codable,Equatable { public var id:String; public var time:Double; public var source:String; public var text:String; public var priority:Int }
public struct EENetworkReplay51:Sendable,Codable,Equatable { public var node:String; public var latencyMS:Double; public var packetLoss:Double; public var stale:Bool }
public struct EEVibrationReplay51:Sendable,Codable,Equatable { public var asset:String; public var overall:Double; public var orders:[Double:Double] }
public struct EEThermalReplay51:Sendable,Codable,Equatable { public var asset:String; public var temperatureC:Double; public var riseC:Double }
public struct EEForensicFrame51:Identifiable,Sendable,Codable,Equatable { public var id:String; public var world:EEIndustrialWorld; public var time:Double; public var process:[String:Double]; public var plc:EEPLCReplay51; public var soe:[EESOEReplayEvent51]; public var network:[EENetworkReplay51]; public var thermal:[EEThermalReplay51]; public var vibration:[EEVibrationReplay51]; public var evidenceIDs:[String] }
public struct EESynchronizedReplay51:Sendable,Codable,Equatable {
 public var gas:[EEForensicFrame51]=[];public var coal:[EEForensicFrame51]=[];public var capacity=14_400;public init(){}
 public mutating func append(_ f:EEForensicFrame51){if f.world == .naturalGas{gas.append(f);if gas.count>capacity{gas.removeFirst(gas.count-capacity)}}else{coal.append(f);if coal.count>capacity{coal.removeFirst(coal.count-capacity)}}}
 public func frames(_ world:EEIndustrialWorld)->[EEForensicFrame51]{world == .naturalGas ? gas:coal}
 public func nearest(_ world:EEIndustrialWorld,time:Double)->EEForensicFrame51?{frames(world).min{abs($0.time-time)<abs($1.time-time)}}
}

public struct EERev51TechnicalCeiling:Sendable,Codable,Equatable {
 public var base=EERev50PhysicalizedForensics();public var bench=EECircuitMNABench51();public var replay=EESynchronizedReplay51();public var scanCounter:[EEIndustrialWorld:Int]=[.naturalGas:0,.coalMining:0]
 public init(){capture(.naturalGas);capture(.coalMining)}
 public var golden:EERegistryCompleteGoldenThread51{.init(base:base.base.golden,timeline:base.base.base.base.base.timeline)}
 public mutating func advance(_ world:EEIndustrialWorld,seconds:Double){if world == .naturalGas{base.base.base.base.base.advanceGas(seconds)}else{base.base.base.base.base.advanceCoal(seconds)};capture(world)}
 public mutating func capture(_ world:EEIndustrialWorld){guard let s=base.base.base.base.base.timeline.snapshots(for:world).last else{return};scanCounter[world,default:0]+=1;let values=Dictionary(uniqueKeysWithValues:s.channels.map{($0.id,$0.value)});let evidence=base.base.evidenceLinks.filter{$0.world==world && abs($0.time-s.time)<0.001}.map{$0.evidenceID};let plc=EEPLCReplay51(scan:scanCounter[world,default:0],tags:values,states:["mode":"RUN","world":world.rawValue]);var soe=s.events.enumerated().map{EESOEReplayEvent51(id:"SOE-\(world.rawValue)-\(s.time)-\($0.offset)",time:s.time,source:"simulation",text:$0.element,priority:2)}
  let network:[EENetworkReplay51];let thermal:[EEThermalReplay51];let vibration:[EEVibrationReplay51]
  if world == .naturalGas {let g=base.base.base.base.base.gas;network=[.init(node:"PLC-GAS",latencyMS:2.0,packetLoss:0,stale:false),.init(node:"VFD-2",latencyMS:2.5,packetLoss:0,stale:false)];thermal=[.init(asset:"COMP-2",temperatureC:g.rev39.base.unit.bearingTempC,riseC:g.rev39.base.unit.bearingTempC-25)];vibration=[.init(asset:"COMP-2",overall:g.rev39.base.unit.vibration,orders:[1:g.rev39.base.unit.vibration,2:g.rev39.base.unit.vibration*0.42])];if g.vfd.dcRippleV>30{soe.append(.init(id:"SOE-GAS-RIPPLE-\(s.time)",time:s.time,source:"VFD-2",text:"Elevated DC bus ripple",priority:2))}
  } else {let c=base.base.base.base.base.coal;let belt=c.rev43.belts[.northRidge];network=[.init(node:"PLC-COAL",latencyMS:3.0,packetLoss:0,stale:false),.init(node:"TLO-RIO",latencyMS:4.0,packetLoss:0,stale:false)];thermal=[.init(asset:"CV-NR-OL",temperatureC:belt?.segments.map{$0.idlerTempC}.max() ?? 25,riseC:max(0,(belt?.segments.map{$0.idlerTempC}.max() ?? 25)-25)),.init(asset:"CENT-101",temperatureC:c.centrifuge.bearingTempC,riseC:c.centrifuge.bearingTempC-25)];vibration=[.init(asset:"CENT-101",overall:c.centrifuge.vibrationMMPS,orders:[1:c.centrifuge.vibrationMMPS,2:c.centrifuge.vibrationMMPS*0.35]),.init(asset:"LW-NR",overall:c.rev43.longwalls[.northRidge]?.shearer.vibrationMMPS ?? 0,orders:[1:c.rev43.longwalls[.northRidge]?.shearer.vibrationMMPS ?? 0])];if (belt?.segments.map{$0.idlerTempC}.max() ?? 0)>80{soe.append(.init(id:"SOE-COAL-IDLER-\(s.time)",time:s.time,source:"CV-NR-OL",text:"High idler temperature",priority:1))}}
  replay.append(.init(id:"F51-\(world.rawValue)-\(s.time)",world:world,time:s.time,process:values,plc:plc,soe:soe,network:network,thermal:thermal,vibration:vibration,evidenceIDs:evidence))
 }
 public func frame(world:EEIndustrialWorld,time:Double)->EEForensicFrame51?{replay.nearest(world,time:time)}
}

// MARK: - Rev52 Total Competitive Assimilation
public enum EEReferenceProduct52:String,CaseIterable,Sendable,Codable { case electricianSimulator, electricianSimulatorVR, electroSim, falstad, everyCircuit, multisim, proteus, crumb, electricVLab, tinkercad, phet }
public enum EEAssimilationDomain52:String,CaseIterable,Sendable,Codable { case career, physicalInteraction, construction, visualization, simulation, instruments, analysis, embedded, training, faults, community, accessibility, industrialization }
public enum EEAssimilationState52:String,Sendable,Codable { case implemented, foundation, planned }
public struct EEAssimilatedFeature52:Identifiable,Sendable,Codable,Equatable { public var id:String;public var source:EEReferenceProduct52;public var domain:EEAssimilationDomain52;public var sourceConcept:String;public var electricEngineerAdaptation:String;public var state:EEAssimilationState52 }
public struct EECompetitiveAssimilationMatrix52:Sendable,Codable,Equatable {
 public var features:[EEAssimilatedFeature52]
 public init(){var f:[EEAssimilatedFeature52]=[];func add(_ s:EEReferenceProduct52,_ d:EEAssimilationDomain52,_ c:String,_ a:String,_ st:EEAssimilationState52 = .foundation){f.append(.init(id:"\(s.rawValue)-\(f.count)",source:s,domain:d,sourceConcept:c,electricEngineerAdaptation:a,state:st))}
  add(.electricianSimulator,.career,"customer jobs","persistent industrial work orders, shift handoff, production impact",.implemented);add(.electricianSimulator,.construction,"parts and repairs","rated parts, installation state, commissioning and proof",.implemented);add(.electricianSimulator,.career,"workshop progression","tool crib, qualifications, consumables and career growth");add(.electricianSimulator,.physicalInteraction,"hands-on repair","physical asset access, covers, terminals and test points",.implemented)
  add(.electricianSimulatorVR,.physicalInteraction,"direct tool manipulation","probe, clamp, sensor and connector placement",.implemented);add(.electricianSimulatorVR,.construction,"direct cable interaction","drag-route-land conductor workflow",.foundation);add(.electricianSimulatorVR,.physicalInteraction,"embodied workspace","spatial rooms, elevations and equipment access",.implemented)
  add(.electroSim,.construction,"terminal-to-terminal wiring","freeform physical terminal graph compiled to CircuitMNA",.implemented);add(.electroSim,.training,"guided circuits","observe, demonstrate, build, measure, commission, diagnose, repair, prove",.implemented);add(.electroSim,.simulation,"real-time wiring simulation","single physical truth with immediate solve",.implemented);add(.electroSim,.community,"saved/shared circuits","deterministic challenge package foundation")
  add(.falstad,.visualization,"animated current","Electrical Vision current vectors and magnitude");add(.falstad,.visualization,"voltage color","potential and voltage-drop overlays");add(.falstad,.simulation,"interactive live circuit","continuous MNA-backed editing",.implemented);add(.falstad,.training,"instant experimentation","safe sandbox with pause/step")
  add(.everyCircuit,.construction,"drag/drop/rotate/flip","production editor operations");add(.everyCircuit,.construction,"undo/redo","deterministic edit command history",.implemented);add(.everyCircuit,.visualization,"live mini waveforms","identity-bound waveform overlays");add(.everyCircuit,.analysis,"frequency response","engineering analysis laboratory");add(.everyCircuit,.community,"searchable circuit library","local/community trainer catalog")
  add(.multisim,.simulation,"mixed-mode SPICE","CircuitMNA real-time core plus deeper analysis solver");add(.multisim,.instruments,"simulation-driven instruments","physical instrument rack with real controls",.implemented);add(.multisim,.analysis,"DC/AC/transient analyses","analysis mode catalog",.implemented);add(.multisim,.analysis,"Monte Carlo and sweeps","tolerance, parameter, temperature and worst-case studies",.foundation);add(.multisim,.faults,"component fault insertion","physical and evolving fault primitives",.implemented);add(.multisim,.construction,"hierarchy/subcircuits","reusable assemblies and trainer modules")
  add(.proteus,.embedded,"firmware co-simulation","MCU/PLC/embedded bench with I/O, timers and buses");add(.proteus,.embedded,"debugger stepping","pause, step, register/tag inspection");add(.proteus,.simulation,"mixed analog/digital","electrical plus logic/network truth");add(.proteus,.instruments,"virtual debugging tools","logic analyzer, serial and CAN analysis")
  add(.crumb,.physicalInteraction,"3D workbench","spatial bench surfaces and physical components",.foundation);add(.crumb,.construction,"physical breadboarding","breadboard/DIN rail/panel placement");add(.crumb,.instruments,"bench instruments","PSU, scope, generator and DMM rack")
  add(.electricVLab,.construction,"build/simulate modes","authoring and energized states",.implemented);add(.electricVLab,.visualization,"3D + schematic","synchronized physical/schematic identity views");add(.electricVLab,.faults,"overload effects","I2t, thermal stress and component damage",.implemented);add(.electricVLab,.instruments,"scope/cursors/trigger","full oscilloscope control model")
  add(.tinkercad,.construction,"low-friction wiring","starter templates, snap targets and guided placement");add(.tinkercad,.embedded,"Arduino-style simulation","embedded-controls laboratory");add(.tinkercad,.training,"starter circuits","progressive templates from battery to plant")
  add(.phet,.training,"safe experimentation","sandbox with reset, pause and step");add(.phet,.visualization,"conventional/electron current","switchable current representation");add(.phet,.accessibility,"non-color state communication","motion, thickness, text, haptics and accessibility labels");add(.phet,.instruments,"movable meter probes","physical probe placement",.implemented)
  for p in EEReferenceProduct52.allCases { add(p,.industrialization,"adapted reference pattern","identity, evidence, degradation, Golden Thread and industrial-world integration",.implemented) }
  features=f
 }
 public func from(_ p:EEReferenceProduct52)->[EEAssimilatedFeature52]{features.filter{$0.source==p}}
 public var sourceCoverage:Double{Double(Set(features.map{$0.source}).count)/Double(EEReferenceProduct52.allCases.count)}
 public var domainCoverage:Double{Double(Set(features.map{$0.domain}).count)/Double(EEAssimilationDomain52.allCases.count)}
}

public enum EELabEnvironment52:String,CaseIterable,Sendable,Codable { case fundamentals, electronics, industrialControls, instrumentation, plcEmbedded, communicationsCAN, engineeringAnalysis }
public enum EEAnalysisMode52:String,CaseIterable,Sendable,Codable { case dcOperatingPoint, dcSweep, transient, acSweep, fourierFFT, noise, parameterSweep, temperatureSweep, monteCarlo, worstCase, sensitivity, transferFunction, poleZero, tolerance, powerEnergy, thermalSweep, failureSweep, protectionCoordination, motorStart, voltageDrop, shortCircuit, loopCompliance, groundFault, phaseImbalance, harmonics, vfdDCBus, relayTiming, networkTiming, canTermination }
public enum EEVisionLayer52:String,CaseIterable,Sendable,Codable { case current, electronFlow, voltage, voltageDrop, acPolarity, rms, phaseAngle, phasors, realPower, reactivePower, apparentPower, powerFactor, charge, magneticState, semiconductorState, digitalState, waveform, pwm, conductorTemperature, terminalTemperature, leakage, insulation, arc, fuseI2T, motorTorque, mechanicalLoad }
public enum EEFaultPrimitive52:String,CaseIterable,Sendable,Codable { case open, short, highResistance, leakage, intermittent, thermalDrift, parameterDrift, contactBounce, weldedContact, capacitanceLoss, esrRise, diodeLeakage, semiconductorBreakdown, fuseAging, looseTermination, corrosion, moisture, insulationDamage, brokenStrands, bearingDrag, vibrationIntermittency, contaminatedConnector, shieldFault, communicationNoise }
public enum EEInstrument52:String,CaseIterable,Sendable,Codable { case dmm, analogMeter, clampMeter, megohmmeter, phaseRotation, oscilloscope, currentProbe, differentialProbe, functionGenerator, dcSupply, acSource, frequencyCounter, spectrumAnalyzer, logicAnalyzer, logicProbe, componentTester, lcrMeter, powerAnalyzer, thermalCamera, loopCalibrator, processCalibrator, pressureCalibrator, rtdSimulator, thermocoupleSimulator, hartCommunicator, vibrationAnalyzer, tachometer, ethernetAnalyzer, serialAnalyzer, canAnalyzer }

public enum EEBenchEditKind52:String,Sendable,Codable { case addComponent, removeComponent, wire, removeWire, enable, energize }
public struct EEBenchEdit52:Identifiable,Sendable,Codable,Equatable { public var id=UUID();public var kind:EEBenchEditKind52;public var label:String;public var before:EECircuitMNABench51;public var after:EECircuitMNABench51 }
public struct EEProductionBench52:Sendable,Codable,Equatable {
 public var core=EECircuitMNABench51();public var undo:[EEBenchEdit52]=[];public var redo:[EEBenchEdit52]=[];public var selectedLab:EELabEnvironment52 = .fundamentals;public var selectedAnalysis:EEAnalysisMode52 = .dcOperatingPoint;public var vision:Set<EEVisionLayer52>=[.current,.voltage];public var injectedFaults:[String:EEFaultPrimitive52]=[:]
 public init(){}
 public mutating func transact(_ kind:EEBenchEditKind52,_ label:String,_ change:(inout EECircuitMNABench51)->Void){let b=core;change(&core);guard core != b else{return};undo.append(.init(kind:kind,label:label,before:b,after:core));redo=[]}
 public mutating func undoLast(){guard let e=undo.popLast() else{return};core=e.before;redo.append(e)}
 public mutating func redoLast(){guard let e=redo.popLast() else{return};core=e.after;undo.append(e)}
 public mutating func inject(_ fault:EEFaultPrimitive52,component:String){injectedFaults[component]=fault;if fault == .open{core.setEnabled(component,false)};if fault == .short,let c=core.workspace.components.first(where:{$0.id==component}),c.terminals.count>=2{_ = core.wire(c.terminals[0],c.terminals[1],resistanceOhm:0.0001)}}
 public mutating func resetFault(_ component:String){injectedFaults.removeValue(forKey:component);core.setEnabled(component,true)}
 public mutating func solve()->EEBenchSolveResult51{core.solve()}
}

public struct EERev52TotalAssimilation:Sendable,Codable,Equatable {
 public var base=EERev51TechnicalCeiling();public var bench=EEProductionBench52();public var matrix=EECompetitiveAssimilationMatrix52();public var instrumentRack=EEInstrument52.allCases;public var analysisModes=EEAnalysisMode52.allCases;public var visionLayers=EEVisionLayer52.allCases;public var faultLibrary=EEFaultPrimitive52.allCases
 public init(){}
 public var goldenAudit:EEGoldenThreadAudit51{base.golden.audit}
}

// MARK: - Rev53 Simulation-Backed Production Behavior
public enum EESignalWaveform53:String,CaseIterable,Sendable,Codable { case dc,sine,square,triangle,pulse }
public struct EEFunctionGenerator53:Sendable,Codable,Equatable { public var waveform:EESignalWaveform53 = .sine;public var amplitudeV=5.0;public var offsetV=0.0;public var frequencyHz=1000.0;public var duty=0.5;public init(){};public func value(at t:Double)->Double{let p=(t*frequencyHz).truncatingRemainder(dividingBy:1);switch waveform{case .dc:return offsetV+amplitudeV;case .sine:return offsetV+amplitudeV*sin(2*Double.pi*frequencyHz*t);case .square:return offsetV+(p<duty ? amplitudeV:-amplitudeV);case .triangle:return offsetV+amplitudeV*(1-4*abs(p-0.5));case .pulse:return offsetV+(p<duty ? amplitudeV:0)}} }
public struct EEOscilloscopeChannel53:Identifiable,Sendable,Codable,Equatable {public var id:String;public var terminal:String;public var voltsPerDivision=1.0;public var samples:[Double]=[]}
public struct EEOscilloscope53:Sendable,Codable,Equatable {public var timePerDivision=0.001;public var triggerLevel=0.0;public var triggerRising=true;public var channels:[EEOscilloscopeChannel53]=[];public init(){};public mutating func capture(id:String,terminal:String,values:[Double]){if let i=channels.firstIndex(where:{$0.id==id}){channels[i].terminal=terminal;channels[i].samples=values}else{channels.append(.init(id:id,terminal:terminal,samples:values))}}}
public struct EETransientTrace53:Sendable,Codable,Equatable {public var times:[Double]=[];public var voltages:[String:[Double]] = [:];public var convergedSteps=0}
public struct EETransientBench53:Sendable,Codable {
 public var capacitors:[String:TransientCapacitor]=[:];public var inductors:[String:TransientInductor]=[:];public var trace=EETransientTrace53();public init(){}
 public mutating func rcStep(sourceV:Double=10,resistance:Double=1000,capacitance:Double=1e-6,dt:Double=0.0001,steps:Int=100)->EETransientTrace53{var cap = capacitors["C1"] ?? makeTransientCapacitor53(capacitance); trace = .init();for k in 0..<max(1,steps){let stamp=cap.stamp(dt:dt,a:1,b:0);let c=Circuit(nodeCount:2,resistors:[.init(a:1,b:0,resistance:resistance),stamp.0],currentSources:[stamp.1],voltageSources:[.init(positive:1,negative:0,volts:sourceV)]);if let s=try? ReferenceDCSolver().solve(c){let v=s.nodeVoltages[1];cap.commit(voltage:v);trace.times.append(Double(k+1)*dt);trace.voltages["C1",default:[]].append(v);trace.convergedSteps += 1}};capacitors["C1"]=cap;return trace}
 public func diodeOperatingPoint(sourceV:Double=5,seriesOhms:Double=1000)->(voltage:Double,iterations:Int,converged:Bool){DiodeNewtonSolver().solve(sourceVolts:sourceV,seriesOhms:seriesOhms)}
}
public struct EEAnalysisResult53:Sendable,Codable,Equatable {public var mode:EEAnalysisMode52;public var x:[Double];public var y:[Double];public var summary:String}
public struct EEAnalysisLab53:Sendable,Codable,Equatable {
 public var results:[EEAnalysisResult53]=[];public init(){}
 public mutating func dcSweep(resistance:Double=1000,start:Double=0,stop:Double=24,points:Int=25)->EEAnalysisResult53{let n=max(2,points);let x=(0..<n).map{start+(stop-start)*Double($0)/Double(n-1)};let y=x.map{$0/max(resistance,1e-9)};let r=EEAnalysisResult53(mode:.dcSweep,x:x,y:y,summary:"DC source sweep through \(resistance) Ω");results.append(r);return r}
 public mutating func acSweepRC(resistance:Double=1000,capacitance:Double=1e-6,startHz:Double=1,stopHz:Double=100_000,points:Int=81)->EEAnalysisResult53{let n=max(2,points);let a=log10(startHz),b=log10(stopHz);let x=(0..<n).map{pow(10,a+(b-a)*Double($0)/Double(n-1))};let y=x.map{f in let w=2*Double.pi*f;return 1/sqrt(1+pow(w*resistance*capacitance,2))};let r=EEAnalysisResult53(mode:.acSweep,x:x,y:y,summary:"RC low-pass magnitude sweep");results.append(r);return r}
 public mutating func monteCarloResistance(nominal:Double=1000,tolerance:Double=0.05,samples:Int=200,seed:UInt64=53)->EEAnalysisResult53{var s=seed;func rnd()->Double{s = 6364136223846793005 &* s &+ 1442695040888963407;return Double(s>>11)/Double(UInt64.max>>11)};let x=(0..<max(1,samples)).map{Double($0)};let y=x.map{_ in nominal*(1+tolerance*(2*rnd()-1))};let r=EEAnalysisResult53(mode:.monteCarlo,x:x,y:y,summary:"Deterministic tolerance Monte Carlo");results.append(r);return r}
}
public enum EEThreePhaseConnection53:String,Sendable,Codable {case wye,delta}
public struct EEThreePhaseTrainer53:Sendable,Codable,Equatable {public var lineVolts=480.0;public var frequencyHz=60.0;public var phaseSequenceABC=true;public var connection:EEThreePhaseConnection53 = .wye;public init(){};public func phaseVoltages(at t:Double)->[Double]{let peak=lineVolts/sqrt(3)*sqrt(2);let w=2*Double.pi*frequencyHz;let sign=phaseSequenceABC ? 1.0:-1.0;return [sin(w*t),sin(w*t-sign*2*Double.pi/3),sin(w*t+sign*2*Double.pi/3)].map{$0*peak}}}
public struct EERelayMechanics53:Sendable,Codable,Equatable {public var coilVolts=0.0;public var ratedVolts=24.0;public var armature=0.0;public var contactResistance=0.02;public var cycles=0;public var welded=false;public init(){};public mutating func step(dt:Double){let target=coilVolts >= 0.7*ratedVolts ? 1.0:0.0;armature += (target-armature)*min(1,dt*30);if armature>0.95 && target>0.5{cycles += 1};contactResistance=min(2,0.02+Double(cycles)*1e-7);if welded{armature=max(armature,0.99)}};public var closed:Bool{armature>0.85||welded}}
public struct EEBreadboard53:Sendable,Codable,Equatable {public var rows=30;public var rails=2;public init(){};public func node(row:Int,column:Int)->String{if column<5{return "BB:L:\(row)"};return "BB:R:\(row)"}}
public enum EEEmbeddedInstruction53:Sendable,Codable,Equatable {case set(String,Double),add(String,Double),copy(String,String),wait(Int)}
public struct EEEmbeddedRuntime53:Sendable,Codable,Equatable {public var pc=0;public var registers:[String:Double]=[:];public var halted=false;public init(){};public mutating func step(_ program:[EEEmbeddedInstruction53]){guard !halted,!program.isEmpty else{return};if pc>=program.count{halted=true;return};switch program[pc]{case let .set(r,v):registers[r]=v;case let .add(r,v):registers[r,default:0]+=v;case let .copy(a,b):registers[b]=registers[a,default:0];case .wait:break};pc += 1;if pc>=program.count{halted=true}}}
public struct EERev53SimulationProduction:Sendable,Codable {public var base=EERev52TotalAssimilation();public var transient=EETransientBench53();public var generator=EEFunctionGenerator53();public var scope=EEOscilloscope53();public var analysis=EEAnalysisLab53();public var threePhase=EEThreePhaseTrainer53();public var relay=EERelayMechanics53();public var breadboard=EEBreadboard53();public var embedded=EEEmbeddedRuntime53();public init(){}}

// MARK: - Rev54 Unified Physical Simulation Ceiling
public enum EEAdvancedDevice54:String,CaseIterable,Sendable,Codable {case inductor,bjtNPN,mosfetN,opAmp}
public struct EEAdvancedComponent54:Identifiable,Sendable,Codable,Equatable {public var id:String;public var kind:EEAdvancedDevice54;public var terminals:[String];public var value:Double;public init(id:String,kind:EEAdvancedDevice54,terminals:[String],value:Double){self.id=id;self.kind=kind;self.terminals=terminals;self.value=value}}
public struct EEAdaptiveStep54:Sendable,Codable,Equatable {public var time:Double;public var dt:Double;public var value:Double;public var iterations:Int}
public struct EEAdaptiveTransient54:Sendable,Codable,Equatable {
 public var minDT=1e-7, maxDT=2e-3, tolerance=1e-4;public var trace:[EEAdaptiveStep54]=[];public init(){}
 public mutating func rc(source:EEFunctionGenerator53=EEFunctionGenerator53(),r:Double=1000,c:Double=1e-6,duration:Double=0.01)->[EEAdaptiveStep54]{trace=[];var t=0.0,v=0.0,dt=min(1e-4,maxDT);while t<duration{let h=min(dt,duration-t);let vin=source.value(at:t+h);let next=(v+h*vin/(r*c))/(1+h/(r*c));let half=h/2;let mid=(v+half*source.value(at:t+half)/(r*c))/(1+half/(r*c));let fine=(mid+half*vin/(r*c))/(1+half/(r*c));let err=abs(fine-next);if err>tolerance && h>minDT*1.01{dt=max(minDT,h/2);continue};v=fine;t+=h;trace.append(.init(time:t,dt:h,value:v,iterations:1));if err<tolerance*0.1{dt=min(maxDT,h*1.6)}};return trace}
}
public struct EENonlinearModels54:Sendable,Codable,Equatable {public init(){};public func bjtCollector(baseV:Double,beta:Double=100)->Double{let ib=max(0,(baseV-0.7)/10_000);return min(0.2,beta*ib)};public func mosfetDrain(gateV:Double,threshold:Double=2.5,k:Double=0.08)->Double{let x=max(0,gateV-threshold);return k*x*x};public func opAmp(vPlus:Double,vMinus:Double,gain:Double=100_000,rails:ClosedRange<Double> = -12...12)->Double{min(rails.upperBound,max(rails.lowerBound,(vPlus-vMinus)*gain))}}
public enum EETriggerMode54:String,Sendable,Codable {case auto,normal,single}
public struct EEScopeMeasurement54:Sendable,Codable,Equatable {public var minimum:Double;public var maximum:Double;public var mean:Double;public var rms:Double;public var frequencyHz:Double?}
public struct EEScopeEngine54:Sendable,Codable,Equatable {public var level=0.0;public var rising=true;public var mode:EETriggerMode54 = .auto;public var cursorA=0,cursorB=0;public init(){};public func triggerIndex(_ x:[Double])->Int?{guard x.count>1 else{return nil};return (1..<x.count).first{rising ? (x[$0-1]<level && x[$0]>=level):(x[$0-1]>level && x[$0]<=level)}};public func measure(_ x:[Double],sampleRate:Double)->EEScopeMeasurement54{guard !x.isEmpty else{return .init(minimum:0,maximum:0,mean:0,rms:0,frequencyHz:nil)};let mean=x.reduce(0,+)/Double(x.count);let rms=sqrt(x.map{$0*$0}.reduce(0,+)/Double(x.count));var crossings=0;for i in 1..<x.count where x[i-1]<mean && x[i]>=mean{crossings += 1};let f=crossings>1 ? Double(crossings-1)*sampleRate/Double(x.count):nil;return .init(minimum:x.min()!,maximum:x.max()!,mean:mean,rms:rms,frequencyHz:f)};public func cursorDelta(sampleRate:Double)->Double{Double(abs(cursorB-cursorA))/sampleRate};public func fftMagnitude(_ x:[Double],bins:Int=32)->[Double]{guard !x.isEmpty else{return []};let n=x.count;return (0..<min(bins,n/2)).map{k in var re=0.0,im=0.0;for i in 0..<n{let a=2*Double.pi*Double(k*i)/Double(n);re += x[i]*cos(a);im -= x[i]*sin(a)};return sqrt(re*re+im*im)/Double(n)}}}
public struct EEElectromechanicalLoop54:Sendable,Codable,Equatable {public var relay=EERelayMechanics53();public var supplyV=24.0;public var coilOhms=240.0;public var loadOhms=24.0;public var loadCurrent=0.0;public init(){};public mutating func step(command:Bool,dt:Double){relay.coilVolts=command ? supplyV:0;relay.step(dt:dt);loadCurrent=relay.closed ? supplyV/max(loadOhms+relay.contactResistance,1e-6):0}}
public struct EEEmbeddedIO54:Sendable,Codable,Equatable {public var runtime=EEEmbeddedRuntime53();public var gpio:[String:Bool]=[:];public var pwm:[String:Double]=[:];public var adc:[String:Double]=[:];public var canTX:[UInt32:[UInt8]]=[:];public init(){};public mutating func writeGPIO(_ id:String,_ high:Bool){gpio[id]=high};public mutating func writePWM(_ id:String,_ duty:Double){pwm[id]=min(1,max(0,duty))};public mutating func sampleADC(_ id:String,nodeVoltage:Double,reference:Double=5){adc[id]=min(1,max(0,nodeVoltage/max(reference,1e-9)))};public mutating func sendCAN(id:UInt32,data:[UInt8]){canTX[id]=Array(data.prefix(8))}}
public struct EEUnifiedBench54:Sendable,Codable,Equatable {public var base=EEProductionBench52();public var advanced:[EEAdvancedComponent54]=[];public var transient=EEAdaptiveTransient54();public var nonlinear=EENonlinearModels54();public var generator=EEFunctionGenerator53();public var scope=EEScopeEngine54();public var electromechanical=EEElectromechanicalLoop54();public var embedded=EEEmbeddedIO54();public init(){};public mutating func addAdvanced(_ c:EEAdvancedComponent54){if !advanced.contains(where:{$0.id==c.id}){advanced.append(c)}};public mutating func runGeneratorRC(duration:Double=0.01)->[EEAdaptiveStep54]{transient.rc(source:generator,duration:duration)}}
public struct EERev54UnifiedSimulation:Sendable,Codable {public var base=EERev53SimulationProduction();public var bench=EEUnifiedBench54();public init(){}}

// MARK: - Rev55 Numerical Credibility Ceiling
public struct EENonlinearConvergence55: Sendable,Codable,Equatable { public var converged:Bool; public var iterations:Int; public var residual:Double; public var limitedSteps:Int }
public struct EENonlinearResult55: Sendable,Codable,Equatable { public var voltage:Double; public var current:Double; public var report:EENonlinearConvergence55 }
public struct EENonlinearMNA55: Sendable,Codable,Equatable {
 public var maxIterations=80; public var voltageTolerance=1e-9; public var residualTolerance=1e-10; public var maxStep=0.35; public init(){}
 private func solveNode(sourceV:Double,sourceR:Double,initial:Double,current:(Double)->Double,conductance:(Double)->Double)->EENonlinearResult55 { var v=initial;var limited=0;var res=Double.infinity;for i in 1...maxIterations{let f=(v-sourceV)/sourceR+current(v);let g=1/sourceR+conductance(v);res=abs(f);if res<residualTolerance{return .init(voltage:v,current:(sourceV-v)/sourceR,report:.init(converged:true,iterations:i,residual:res,limitedSteps:limited))};var dv = -f/max(abs(g),1e-15);if abs(dv)>maxStep{dv=maxStep*(dv<0 ? -1:1);limited += 1};v += dv;if abs(dv)<voltageTolerance && res<residualTolerance*10{return .init(voltage:v,current:(sourceV-v)/sourceR,report:.init(converged:true,iterations:i,residual:res,limitedSteps:limited))}};return .init(voltage:v,current:(sourceV-v)/sourceR,report:.init(converged:false,iterations:maxIterations,residual:res,limitedSteps:limited)) }
 public func diode(sourceV:Double=5,sourceR:Double=1000,isat:Double=1e-12,n:Double=1)->EENonlinearResult55 {let vt=0.025852*n;return solveNode(sourceV:sourceV,sourceR:sourceR,initial:min(0.7,sourceV),current:{v in isat*(exp(min(v/vt,40))-1)},conductance:{v in isat/vt*exp(min(v/vt,40))})}
 public func mosfetDiodeConnected(sourceV:Double=5,sourceR:Double=1000,vth:Double=2,k:Double=0.002)->EENonlinearResult55 {solveNode(sourceV:sourceV,sourceR:sourceR,initial:min(sourceV,vth+0.5),current:{v in let x=max(0,v-vth);return 0.5*k*x*x},conductance:{v in k*max(0,v-vth)})}
 public func bjtDiodeConnected(sourceV:Double=5,sourceR:Double=1000,isat:Double=1e-15,beta:Double=100)->EENonlinearResult55 {let vt=0.025852;return solveNode(sourceV:sourceV,sourceR:sourceR,initial:0.7,current:{v in (beta+1)*isat*(exp(min(v/vt,40))-1)},conductance:{v in (beta+1)*isat/vt*exp(min(v/vt,40))})}
 public func opAmpFollower(input:Double,positiveRail:Double=12,negativeRail:Double = -12,openLoopGain:Double=100_000)->EENonlinearResult55 {let out=min(positiveRail,max(negativeRail,input*openLoopGain/(1+openLoopGain)));return .init(voltage:out,current:0,report:.init(converged:true,iterations:1,residual:abs(out-input),limitedSteps:0))}
}
public enum EEDynamicKind55:String,Sendable,Codable {case resistor,capacitor,inductor}
public struct EEDynamicDevice55:Identifiable,Sendable,Codable,Equatable {public var id:String;public var kind:EEDynamicKind55;public var value:Double;public var state:Double=0;public init(id:String,kind:EEDynamicKind55,value:Double){self.id=id;self.kind=kind;self.value=value}}
public struct EEDynamicDeviceCompiler55:Sendable,Codable,Equatable {public var devices:[EEDynamicDevice55]=[];public var outputV=0.0;public init(){};public mutating func add(_ d:EEDynamicDevice55){devices.append(d)};public mutating func stepSeries(sourceV:Double,dt:Double)->Double{let r=max(devices.filter{$0.kind == .resistor}.map{$0.value}.reduce(0,+),1e-9);if let ci=devices.firstIndex(where:{$0.kind == .capacitor}){let c=max(devices[ci].value,1e-15);let old=devices[ci].state;let v=(old+dt*sourceV/(r*c))/(1+dt/(r*c));devices[ci].state=v;outputV=v;return v};if let li=devices.firstIndex(where:{$0.kind == .inductor}){let l=max(devices[li].value,1e-15);let oldI=devices[li].state;let i=(oldI+dt*sourceV/l)/(1+dt*r/l);devices[li].state=i;outputV=i*r;return outputV};outputV=sourceV;return outputV}}
public enum EEScopeCoupling55:String,Sendable,Codable {case dc,ac,ground}
public enum EEScopeAcquire55:String,Sendable,Codable {case sample,average,peakDetect,highResolution}
public enum EEFFTWindow55:String,Sendable,Codable {case rectangular,hann,hamming,blackman}
public struct EEProfessionalScope55:Sendable,Codable,Equatable {public var sampleRate=100_000.0;public var pretriggerFraction=0.25;public var holdoff=0.0;public var coupling:EEScopeCoupling55 = .dc;public var attenuation=1.0;public var bandwidthHz=20_000_000.0;public var acquisition:EEScopeAcquire55 = .sample;public var window:EEFFTWindow55 = .hann;public var cursorA=0;public var cursorB=0;public init(){};public func condition(_ x:[Double])->[Double]{guard !x.isEmpty else{return []};if coupling == .ground{return Array(repeating:0,count:x.count)};let mean=x.reduce(0,+)/Double(x.count);let base=coupling == .ac ? x.map{$0-mean}:x;return base.map{$0*attenuation}};public func interpolate(_ x:[Double],at index:Double)->Double{guard !x.isEmpty else{return 0};let a=max(0,min(x.count-1,Int(floor(index)))),b=max(0,min(x.count-1,a+1)),f=index-Double(a);return x[a]*(1-f)+x[b]*f};public func windowed(_ x:[Double])->[Double]{let n=max(1,x.count-1);return x.enumerated().map{i,v in let q=2*Double.pi*Double(i)/Double(n);let w:Double;switch window{case .rectangular:w=1;case .hann:w=0.5-0.5*cos(q);case .hamming:w=0.54-0.46*cos(q);case .blackman:w=0.42-0.5*cos(q)+0.08*cos(2*q)};return v*w}};public func xy(_ x:[Double],_ y:[Double])->[(Double,Double)]{Array(zip(x,y))};public func math(_ a:[Double],_ b:[Double],subtract:Bool=false)->[Double]{zip(a,b).map{subtract ? $0-$1:$0+$1}}}
public struct EEElectromechanical55:Sendable,Codable,Equatable {public var ratedV=24.0,coilR=240.0,armature=0.0,velocity=0.0,springK=18.0,residual=0.02,coilTempC=25.0,contactR=0.02,erosion=0.0;public var welded=false;public var chatterCount=0;public init(){};public mutating func step(voltage:Double,loadCurrent:Double=0,dt:Double=0.001){let hotR=coilR*(1+0.00393*(coilTempC-20));let i=voltage/max(hotR,1e-9);let magnetic=5000*i*i+residual;let spring=springK*armature;let accel=(magnetic-spring-1.8*velocity);velocity += accel*dt;armature=min(1,max(0,armature+velocity*dt));coilTempC += ((i*i*hotR)*0.02-(coilTempC-25)*0.08)*dt;if armature>0.82 && armature<0.9{chatterCount += 1};if closed{erosion += abs(loadCurrent)*dt*1e-5;contactR=0.02+erosion};if loadCurrent>40 && closed{welded=true}};public var closed:Bool{welded || armature>0.86}}
public enum EEBus55:String,Sendable,Codable {case uart,spi,i2c,can}
public struct EEEmbeddedHardware55:Sendable,Codable,Equatable {public var supplyV=5.0;public var gpioHighR=25.0;public var gpioLowR=18.0;public var pullups:[String:Double]=[:];public var pulldowns:[String:Double]=[:];public var pwmDuty:[String:Double]=[:];public var adcInputOhms=1_000_000.0;public var timerTicks:UInt64=0;public var interrupts:[String:Int]=[:];public var buses:[EEBus55:[UInt8]]=[:];public var canTerminationA=120.0,canTerminationB=120.0;public init(){};public mutating func tick(_ n:UInt64=1){timerTicks += n};public mutating func interrupt(_ id:String){interrupts[id,default:0]+=1};public func gpioLoadedVoltage(high:Bool,loadOhms:Double)->Double{high ? supplyV*loadOhms/(loadOhms+gpioHighR):0};public func adcSample(nodeV:Double)->Double{nodeV*adcInputOhms/(adcInputOhms+1000)};public mutating func transmit(_ bus:EEBus55,data:[UInt8]){buses[bus]=data};public var canEquivalentTermination:Double{1/(1/canTerminationA+1/canTerminationB)}}
public struct EEGoldenCase55:Identifiable,Sendable,Codable,Equatable {public var id:String;public var expected:Double;public var actual:Double;public var tolerance:Double;public var category:String;public var passed:Bool{abs(expected-actual)<=tolerance}}
public struct EEGoldenCircuitCorpus55:Sendable,Codable,Equatable {public var cases:[EEGoldenCase55]=[];public init(){};public mutating func run(){cases=[];cases.append(.init(id:"DC-divider",expected:5,actual:10*1000/(1000+1000),tolerance:1e-12,category:"DC"));let diode=EENonlinearMNA55().diode();cases.append(.init(id:"Diode-1k-5V",expected:0.574147,actual:diode.voltage,tolerance:0.015,category:"nonlinear"));var d=EEDynamicDeviceCompiler55();d.add(.init(id:"R",kind:.resistor,value:1000));d.add(.init(id:"C",kind:.capacitor,value:1e-6));var v=0.0;for _ in 0..<1000{v=d.stepSeries(sourceV:10,dt:1e-6)};cases.append(.init(id:"RC-one-tau",expected:10*(1-exp(-1)),actual:v,tolerance:0.01,category:"transient"));var l=EEDynamicDeviceCompiler55();l.add(.init(id:"R",kind:.resistor,value:10));l.add(.init(id:"L",kind:.inductor,value:0.1));var vr=0.0;for _ in 0..<1000{vr=l.stepSeries(sourceV:10,dt:1e-5)};cases.append(.init(id:"RL-one-tau",expected:10*(1-exp(-1)),actual:vr,tolerance:0.01,category:"transient"))};public var passed:Bool{!cases.isEmpty && cases.allSatisfy{$0.passed}}}
public struct EERev55NumericalCredibility:Sendable,Codable {public var base=EERev54UnifiedSimulation();public var nonlinear=EENonlinearMNA55();public var dynamics=EEDynamicDeviceCompiler55();public var scope=EEProfessionalScope55();public var electromechanical=EEElectromechanical55();public var embedded=EEEmbeddedHardware55();public var corpus=EEGoldenCircuitCorpus55();public init(){}}
