import Foundation
import ElectricalCore
import CircuitMNA

public struct PanelPoint: Sendable, Codable, Equatable { public var x:Double; public var y:Double; public init(_ x:Double,_ y:Double){self.x=x;self.y=y} }
public struct PanelSize: Sendable, Codable, Equatable { public var width:Double; public var height:Double; public init(_ width:Double,_ height:Double){self.width=width;self.height=height} }
public enum PanelDeviceKind:String,Sendable,Codable { case disconnect, breaker, fuse, transformer, contactor, overload, vfd, plc, ioModule, powerSupply, terminalBlock, relay, hmi, instrument, wireDuct, dinRail }
public struct PanelDevice:Identifiable,Sendable,Codable,Equatable { public var id:String; public var kind:PanelDeviceKind; public var position:PanelPoint; public var size:PanelSize; public var heatWatts:Double; public var clearanceMM:Double; public init(id:String,kind:PanelDeviceKind,position:PanelPoint,size:PanelSize,heatWatts:Double=0,clearanceMM:Double=10){self.id=id;self.kind=kind;self.position=position;self.size=size;self.heatWatts=heatWatts;self.clearanceMM=clearanceMM} }
public enum PanelDesignIssue:String,Sendable,Codable,Equatable { case overlap, outsideEnclosure, insufficientClearance, excessiveHeatDensity, mixedVoltageRouting }
public struct PanelDesignReport:Sendable,Equatable { public var issues:[PanelDesignIssue]; public var heatWatts:Double; public var occupiedFraction:Double; public var valid:Bool{issues.isEmpty} }
public struct ControlPanelLayout:Sendable,Codable,Equatable {
 public var enclosure=PanelSize(800,1000); public var devices:[PanelDevice]=[]
 public init(){}
 public mutating func add(_ d:PanelDevice){devices.append(d)}
 public func validate()->PanelDesignReport { var issues:[PanelDesignIssue]=[]; var area=0.0; let totalHeat=devices.reduce(0){$0+$1.heatWatts}; for d in devices { area += d.size.width*d.size.height; if d.position.x < 0 || d.position.y < 0 || d.position.x+d.size.width > enclosure.width || d.position.y+d.size.height > enclosure.height { issues.append(.outsideEnclosure) } }; for i in devices.indices { for j in devices.indices where j>i { let a=devices[i],b=devices[j]; let overlap=a.position.x < b.position.x+b.size.width && a.position.x+a.size.width > b.position.x && a.position.y < b.position.y+b.size.height && a.position.y+a.size.height > b.position.y; if overlap {issues.append(.overlap)} } }; if totalHeat/(enclosure.width*enclosure.height/1_000_000) > 500 {issues.append(.excessiveHeatDensity)}; return .init(issues:Array(Set(issues)),heatWatts:totalHeat,occupiedFraction:area/(enclosure.width*enclosure.height)) }
}

public enum ConductorClass:String,Sendable,Codable { case power480, control120, control24DC, analog, network, ground }
public struct RoutedWire:Identifiable,Sendable,Codable,Equatable { public var id:String; public var from:String; public var to:String; public var conductorClass:ConductorClass; public var lengthMM:Double; public var gaugeMM2:Double; public init(id:String,from:String,to:String,conductorClass:ConductorClass,lengthMM:Double,gaugeMM2:Double){self.id=id;self.from=from;self.to=to;self.conductorClass=conductorClass;self.lengthMM=lengthMM;self.gaugeMM2=gaugeMM2} }
public struct WireDuct:Sendable,Codable,Equatable { public var capacityMM2:Double=2500; public var wires:[RoutedWire]=[]; public init(){}; public var fillFraction:Double { wires.reduce(0){$0+$1.gaugeMM2*2.2}/max(capacityMM2,1) }; public var overfilled:Bool {fillFraction>0.5} }

public enum LadderInstruction:Sendable,Codable,Equatable { case xic(String), xio(String), ote(String), otl(String), otu(String), ton(tag:String,preset:Double), ctu(tag:String,preset:Int), mov(source:String,destination:String), scale(source:String,destination:String,inMin:Double,inMax:Double,outMin:Double,outMax:Double) }
public struct PLCTimer:Sendable,Codable,Equatable { public var accumulated=0.0; public var preset:Double; public var done=false; public mutating func step(enabled:Bool,dt:Double){if enabled{accumulated+=dt}else{accumulated=0};done=accumulated>=preset} }
public struct PLCCounter:Sendable,Codable,Equatable { public var accumulated=0; public var preset:Int; public var done=false; public var last=false; public mutating func step(_ input:Bool){if input && !last{accumulated+=1};last=input;done=accumulated>=preset} }
public struct AutomationRuntime:Sendable {
 public var bools:[String:Bool]=[:]; public var reals:[String:Double]=[:]; public var timers:[String:PLCTimer]=[:]; public var counters:[String:PLCCounter]=[:]; public var firstScan=true; public var scanTime=0.010
 public init(){}
 public mutating func execute(_ rung:[LadderInstruction],dt:Double?=nil){ var power=true; let step=dt ?? scanTime; for ins in rung { switch ins { case .xic(let t): power = power && (bools[t] ?? false); case .xio(let t): power = power && !(bools[t] ?? false); case .ote(let t): bools[t]=power; case .otl(let t): if power{bools[t]=true}; case .otu(let t): if power{bools[t]=false}; case .ton(let tag,let preset): var timer=timers[tag] ?? .init(preset:preset); timer.preset=preset; timer.step(enabled:power,dt:step); timers[tag]=timer; bools[tag+".DN"]=timer.done; case .ctu(let tag,let preset): var c=counters[tag] ?? .init(preset:preset); c.preset=preset; c.step(power); counters[tag]=c; bools[tag+".DN"]=c.done; case .mov(let s,let d): if power{reals[d]=reals[s] ?? 0}; case .scale(let s,let d,let i0,let i1,let o0,let o1): if power{let x=reals[s] ?? 0; reals[d]=o0+(x-i0)/max(i1-i0,1e-12)*(o1-o0)} } }; firstScan=false }
}

public enum IOModuleKind:String,Sendable,Codable { case digitalInput, digitalOutput, analogInput, analogOutput }
public struct IOChannel:Sendable,Codable,Equatable { public var tag:String; public var kind:IOModuleKind; public var fieldValue:Double; public var forcedValue:Double?; public var openWire=false; public var shorted=false; public init(tag:String,kind:IOModuleKind,fieldValue:Double=0){self.tag=tag;self.kind=kind;self.fieldValue=fieldValue}; public var observedValue:Double { if let f=forcedValue{return f}; if openWire{return 0}; if shorted{return kind == .analogInput ? 32767 : 1}; return fieldValue } }

public enum AlarmPriority:Int,Sendable,Codable { case advisory=1, warning=2, trip=3, emergency=4 }
public struct AlarmEvent:Identifiable,Sendable,Codable,Equatable { public var id:String; public var timestamp:Double; public var priority:AlarmPriority; public var message:String; public var acknowledged=false; public init(id:String,timestamp:Double,priority:AlarmPriority,message:String){self.id=id;self.timestamp=timestamp;self.priority=priority;self.message=message} }
public struct TrendSample:Sendable,Codable,Equatable { public var time:Double; public var value:Double; public init(time:Double,value:Double){self.time=time;self.value=value} }
public struct AlarmHistorian:Sendable,Codable,Equatable { public var events:[AlarmEvent]=[]; public var samples:[String:[TrendSample]] = [:]; public init(){}; public mutating func alarm(_ e:AlarmEvent){events.append(e)}; public mutating func sample(tag:String,time:Double,value:Double){samples[tag,default:[]].append(.init(time:time,value:value)); if samples[tag]!.count>1000{samples[tag]!.removeFirst(samples[tag]!.count-1000)}} }

public enum SafetyState:String,Sendable,Codable { case safe, guardOpen, estop, fault, resetRequired }
public struct SafetyRelayRuntime:Sendable,Codable,Equatable { public var channelA=true, channelB=true, estopHealthy=true, reset=false, state:SafetyState = .safe; public init(){}; public mutating func scan(){ if !estopHealthy{state = .estop;return}; if !channelA || !channelB{state = .guardOpen;return}; if state != .safe && !reset{state = .resetRequired;return}; state = .safe; reset=false }; public var outputEnabled:Bool{state == .safe} }

public struct PanelBuildCell:Sendable { public var panel=ControlPanelLayout(); public var duct=WireDuct(); public var plc=AutomationRuntime(); public var drive=IndustrialDriveCell(); public var safety=SafetyRelayRuntime(); public var historian=AlarmHistorian(); public var time=0.0; public init(){}; public mutating func step(start:Bool,stop:Bool,speedHz:Double,load:Double,dt:Double)->(rpm:Double,current:Double){time += dt; safety.scan(); plc.bools["START"]=start; plc.bools["STOP"]=stop; plc.bools["SAFE"]=safety.outputEnabled; plc.execute([.xic("SAFE"),.xic("START"),.xio("STOP"),.ote("RUN")],dt:dt); let run=plc.bools["RUN"] ?? false; let x=drive.step(start:run,stop:!safety.outputEnabled || stop,overloadTrip:false,speedCommandHz:speedHz,loadFraction:load,dt:dt); historian.sample(tag:"MOTOR_RPM",time:time,value:x.rpm); historian.sample(tag:"MOTOR_AMPS",time:time,value:x.current); if drive.overload.tripped && !historian.events.contains(where:{$0.id=="OL1"}) { historian.alarm(.init(id:"OL1",timestamp:time,priority:.trip,message:"Motor overload tripped")) }; return(x.rpm,x.current) } }
